### ISSUE TITLE
Presets of channels get lost

### ISSUE THREAD

**Issue by anzuwi** [File-New-Project/EarTrumpet#512] opened 2020-06-02 23:11 UTC
Hi,

after updating to Win 10, Ver 2004 Ear Trumpet doesn't save the presets (last volume setting) of my apps. E.g. Candy Crash was set to 5%. Closing Candy Crush and reopening it, will reset the volume to 100%. Before 2004 last setting was applied.

Regards
Andreas

**Comment by anzuwi** [comment] 2020-06-04 01:19
Went back to Win 10 Ver 1909 - fixed.

**Comment by topps13** [comment] 2020-06-09 17:18
Seeing the same issue on 2004 with Microsoft Sudoku app. From what I can tell, only impacts Windows Store apps, not x86 apps.

**Comment by andrescirulo** [comment] 2020-06-11 16:22
I'm also seeing the same behaviour. After updating to Win 10 Ver 2004 settings get lost.
As @topps13 says, it appears to be only on Windows Store apps, like Candy Crush or Skype. On x86 apps the settings are keeped.

**Comment by MadLostSoul** [comment] 2020-06-20 15:12
Ich habe das Verhalten hier bei einigen Exoten.

Beispiele:
Liquidsoap v1.1.1 [savonet_liquidsoap](https://github.com/savonet/liquidsoap)
Alle Chrome Versionen (dev, beta, regular)
Alle Opera Versionen (dev, beta, regular)

Es gibt auch Programme wo der Pegel nach einem Programm Neustart erhalten bleibt:
VLC
OBS
Thunderbird

Bei den oben aufgeführten Beispielen hat vor langer Zeit auch mal alles problemlos funktioniert.

**Comment by Giorgi** [comment] 2020-06-21 18:35
For me it doesn't remember volume of Viber neither which is an ordinary x86 app.

**Comment by CosimoMatassini** [comment] 2020-08-17 09:59
Google Chrome doesn't work properly for me. Every time I open it the volume is reset to 100% since I updated to 2004 version. Hope to an update asap.

**Comment by riverar** [comment] 2020-08-30 22:55
@CosimoMatassini I can't reproduce with `Chrome Version 85.0.4183.83 (Official Build) (64-bit)` and `Windows 10 19041.450`. What builds of Chrome/Windows are you using?

**Comment by CosimoMatassini** [comment] 2020-08-30 23:07
I've just updated chrome from 84.0.4147.135 to 85.0.4183.83 but the problem is still there. It appeared when I updated windows from 1909 to 2004. I'm currently using Windows 10 19041.450

**Comment by riverar** [comment] 2020-08-30 23:28
@CosimoMatassini OK, strange.

Please file a bug in Feedback Hub under [Devices and Drivers] - [Audio and sound]. You can cut and paste from this template (but verify the steps apply to you). Please also check ☑ Save a local copy of diagnostics and attachments created when giving feedback. Send a copy of that data to `team@eartrumpet.app` and reference `issue 512`.

```
Summary: Windows does not remember audio levels for application ____

Explain in more detail:
When I start my application, its audio level is reset to 100%,
requiring me to change it again.

Repro steps:
  1. Start application ____
  2. Set audio level to 25%
  3. Close application and restart machine
  4. Start application ____
  5. Observe audio level has reset to 100%

See also: EarTrumpet/issues/512
```

Then paste a link here and I'll forward it directly to the audio team.

**Comment by CosimoMatassini** [comment] 2020-08-30 23:34
Instagram for PC installed from the Microsoft Store has this problem too. If it could help...

**Comment by CosimoMatassini** [comment] 2020-08-31 09:04
https://aka.ms/AA9ijk5

**Comment by riverar** [comment] 2020-08-31 09:55
@CosimoMatassini Thanks, do you have the local copy of the diagnostic data available for us to review?

**Comment by CosimoMatassini** [comment] 2020-08-31 09:57
I' ve lots in that dir, but I cannot recognise the right one

**Comment by riverar** [comment] 2020-08-31 10:02
@CosimoMatassini Find `051b7e83-c147-42f1-9327-5573ba27e569`.

**Comment by CosimoMatassini** [comment] 2020-08-31 10:33
It's protected, so I changed owner to be able to zip it and sent it by email. Why does it increase its size by 20 times?

**Comment by CosimoMatassini** [comment] 2020-08-31 11:00
I' m sending the zip file to the email team@eartrumpet.app

Thank you very much for spending time helping me.
I checked that italian language is not supported yet. So I'm about to open a feature request because I'm able to translate everything. If you want I can help you. It's important to me to make the app better.

**Comment by riverar** [comment] 2020-08-31 20:44
@CosimoMatassini Thanks! No PR needed, we have Italian already. https://crowdin.com/project/eartrumpet/it# Is it not working for you?

**Comment by MadLostSoul** [comment] 2020-09-05 00:47
Sorry for the late reply but I can reproduce the problem to this day just as @CosimoMatassini did. 

From the date of my first post the error has persisted until today. Even the list of programs that work or not work has not changed.

Current Chrome: Version 85.0.4183.83 (Official Build) (64-Bit)
Current Windows: Windows 10 Pro Insider Preview - Version 2004 (Build 20180.1000)

The program that is most important to me runs as a system service but is just a simple x86 exe in quiet mode:
LiquidSoap v1.1.1. --- repo: savonet/liquidsoap

I know that this version is not the latest version of LiquidSoap, but Eartrump has worked correctly in older Windows versions. Unfortunately I cannot say which version of Windows 10 it was.

If desired, I can provide more information (possibly with your instructions).

**Comment by CosimoMatassini** [comment] 2020-09-30 18:28
Any updates?

**Comment by MadLostSoul** [comment] 2020-10-15 09:34
Is the solution still being worked on?

**Comment by CosimoMatassini** [comment] 2020-10-15 12:54
Yes, I hope

**Comment by riverar** [comment] 2020-10-15 16:19
Connected @CosimoMatassini with a Microsoft engineer on Sep 30 but that email thread seems to have gone silent. Will ping folks again.

**Comment by CosimoMatassini** [comment] 2020-10-23 19:04
I just noticed that the problem is related to WASAPI.

**Comment by riverar** [comment] 2020-11-11 08:40
@CosimoMatassini Haven't heard back via email, just checking in.

**Comment by MadLostSoul** [comment] 2021-01-21 08:45
After a new Windows installation, an Insider Preview, the volume settings will no longer be saved for any program.

**Comment by riverar** [comment] 2023-01-26 22:15
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (Windows has the responsibility of remembering audio levels. We'll make sure EarTrumpet Actions lets you at least set up an automated Action for this yourself.) Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 22:15 UTC
Labels: type: windows-bug
