### ISSUE TITLE
Settings Menu Dragging Window Bug

### ISSUE THREAD

**Issue by Celuni** [File-New-Project/EarTrumpet#627] opened 2021-02-02 02:14 UTC
When dragging the Settings window it's really really slow, like its blocking a thread, msg loop or something.

**Comment by jonaskohl** [comment] 2021-02-02 09:15
Duplicate of #349

**Comment by riverar** [comment] 2021-02-03 05:20
Thanks, yep dupe.

**Closed by riverar** 2021-02-03 05:20 UTC
