### ISSUE TITLE
ui does strech horizontally too much  if win10 scale to 125%

### ISSUE THREAD

**Issue by solaroi** [File-New-Project/EarTrumpet#439] opened 2019-11-18 15:28 UTC
1080p 23.8inch display; win10 set display to scale to 125%, then there is too much useless margin on both sides.
![image](https://user-images.githubusercontent.com/38696405/69065191-50f83680-0a5a-11ea-9d29-0a86bd4ed761.png)

**Comment by riverar** [comment] 2019-11-18 21:30
Hi @solaroi, few questions:
* What version of EarTrumpet are you using? (Settings > General > About)
* What build/version of Windows 10 are you using? (Start > Run > winver)
* Can you confirm you're running at 1920x1080 at 125% scaling?

**Comment by solaroi** [comment] 2019-11-19 17:29
version: 2.1.5.0
win10 version: 1903(build 18362.295)
the main display i use is 23.8 inch 1920x1080 and scale to 125%
the problem can be solved by restart eartrumpet. but the over-scaled ui could appear again after several times of system logout login sleep awake(that's all i have done to this laptop). currently, it gets worse than last time i clicked the icon:

![image](https://user-images.githubusercontent.com/38696405/69170255-c0425900-0b34-11ea-9f01-2fa19f70801d.png)
(this is a full screen shot)

**Comment by riverar** [comment] 2019-11-26 00:33
@solaroi Can't reproduce this. Can you try updating Windows 10? You're missing a few updates. Any special customization apps installed? Can you reproduce this 100% of the time?

**Comment by solaroi** [comment] 2019-11-27 07:26
no, i have no specific steps to reproduce it(it happens randomly after system sleep and wake up). it did not happen in my desktop which has the same system updated regularly. the only thing I am sure is that relaunch the app would fix it. there is no "special customization apps"  installed. since it seems that this happens very rarely, i suggest just close this issue for now.  
(by the time of this writing, it gets worse that last time)
![image](https://user-images.githubusercontent.com/38696405/69702435-2f6a0f80-112a-11ea-90c4-d5487b77b209.png)

**Comment by riverar** [comment] 2019-11-27 07:49
Actually, let's leave this open just in case others are having the same issue. In the meantime, we'll keep trying to reproduce it here. Looks like a potential Windows issue. (Can you try installing the latest Windows updates?)

**Comment by riverar** [comment] 2021-02-24 08:24
Closing. We can't reproduce this. Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. Thanks!

**Closed by riverar** 2021-02-24 08:24 UTC
Labels: status: can't reproduce
