### ISSUE TITLE
Volume randomly fluctuation back and forth between set volume and exactly 20% lower than what its set to.

### ISSUE THREAD

**Issue by LandonTheLightsome** [File-New-Project/EarTrumpet#1177] opened 2022-06-20 20:06 UTC
### Summary

Volume keeps fluctuating between the set value and exactly 20% less than the set volume back and forth. Everything except the set windows volume, system volume, and for some reason Discord is affected. I thought it was just visual for a while until today where I realized the volume is actually going up and down.

### Steps to reproduce

It's automatic at all times going up and down.

### EarTrumpet version

EarTrumpet 2.2.0.0

### Windows version

10.0.19044.1766

### Additional information

![Screenshot 2022-06-20 160021](https://user-images.githubusercontent.com/44343572/174671140-f3ac413e-f23e-4ddb-820f-f7b6abb6c97c.png)
![Screenshot 2022-06-20 160046](https://user-images.githubusercontent.com/44343572/174671149-6f2aae40-8d5c-40b3-b0b5-9e273541e821.png)

**Comment by LandonTheLightsome** [comment] 2022-06-20 20:08
I just noticed that when right clicking discord, it has a sub category that IS affected even if it's initial volume isnt.
![Screenshot 2022-06-20 160726](https://user-images.githubusercontent.com/44343572/174671413-dbcab63d-a5d1-4984-8638-f5e429a73917.png)

**Comment by 1024mb** [comment] 2022-07-09 05:52
I'm having a similar issue, in my case the volume is going from 100 to 39 back and forth randomly, even when having the EarTrumpet window open the changes are visible.

**Comment by riverar** [comment] 2022-08-21 04:04
Can you please restart EarTrumpet, then reproduce the issue (or wait), then collect fresh troubleshooting data (from Settings > General) and attach it here? I can't reproduce this yet.

**Comment by HydrantHunter** [comment] 2023-01-27 19:07
If the volume changes when you or someone else speaks in Discord (or possibly in certain instances where other sound is coming through via Discord) then this is almost certainly a Discord setting.  If you've already turned off volume attenuation in Windows Communication settings, then check Discord settings, Voice & Video, and scroll down to Attenuation (there will be a slider and two switches).  Either move the slider all the way to the left or turn off both switches.  That *should* resolve the issue.

**Comment by Ansem93** [comment] 2023-03-06 21:39
This solved it for me! Not sure if there is a workaround. Otherwise I would maybe add a prompt in EarTrumpets to warn users

**Comment by riverar** [comment] 2023-03-06 21:54
Thanks for following up @Ansem93, will close this one!

**Closed by riverar** 2023-03-06 21:54 UTC
