### ISSUE TITLE
Windows freezes

### ISSUE THREAD

**Issue by wp231** [File-New-Project/EarTrumpet#862] opened 2021-06-20 12:53 UTC
## Description
Drag and drop to move this window will be very slow, delayed, and stuck

## Steps to reproduce
Right click on the toolbar icon and select Volume mixer

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 20H2

## Screenshots
![image](https://user-images.githubusercontent.com/56443833/122674616-8ce01880-d208-11eb-80f7-d3b4efdc48ed.png)

**Comment by riverar** [comment] 2021-06-20 19:27
Duplicate of #349, thanks.

**Closed by riverar** 2021-06-20 19:27 UTC
Labels: type: bug
