### ISSUE TITLE
EarTrumpet dialog does not always popup on click.

### ISSUE THREAD

**Issue by luffykazuma** [File-New-Project/EarTrumpet#438] opened 2019-11-06 14:33 UTC
Using the 2.1.5.0 version of EarTrumpet.

The dialog box doesn't always show up on click. It will sometimes show up on the second click, but many times it won't even show up after three to four clicks.

![image](https://i.imgur.com/lCaumz9.gif)

**Comment by JamTarty** [comment] 2019-11-11 16:43
Can confirm this is happening to me as well. Will duplicate if necessary.

**Comment by davuxcom** [comment] 2019-11-16 09:59
Settings / About / Collecting troubleshooting information.

Log should have timestamps about mouse events - do they match up?

**Comment by riverar** [comment] 2019-11-26 00:34
@luffykazuma @JamTarty Any updates on this? Is this happening on a non-primary display?

**Comment by luffykazuma** [comment] 2019-11-26 04:14
I installed EarTrumpet on another laptop, and this problem does not seem to appear in that one. Only using primary laptop display in both instances.

**Comment by luffykazuma** [comment] 2019-11-27 03:31
@davuxcom Here are the timestamps of the delayed open:

19:30:00.763 UI FlyoutViewModel ChangeState Opening
19:30:00.767 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=13242990, Size=[Left=0,Top=1040,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1040} Primary=True DeviceName=\\.\DISPLAY1
19:30:02.110 UI FlyoutViewModel ChangeState Open
19:30:03.667 UI FlyoutViewModel ChangeState Closing_Stage1
19:30:03.686 UI FlyoutViewModel ChangeState Closing_Stage2
19:30:03.990 UI FlyoutViewModel ChangeState Hidden

**Comment by luffykazuma** [comment] 2019-11-27 03:36
I am also facing a similar problem with the normal Windows start menu as well (not caused by EarTrumpet), where there would be an occasional 2 second delay between pressing the Windows key, and the start menu opening. Perhaps there is a link between these two.

**Comment by tech189** [comment] 2021-03-22 13:23
This happens to me too on an external display used in 'Second screen only' mode connected to my laptop with lid shut. It also sometimes happens when right clicking EarTrumpet.

**Comment by ReflexivR** [comment] 2021-06-24 18:44
Can confirm this has something to do with multiple monitors. I was experiencing the same behavior as OP. Turning off the second monitor and changing "multiple displays" setting to "show only on 1" had no effect until restarting EarTrumpet.exe.

**Comment by the-simian** [comment] 2022-03-03 22:40
I can confirm this is happening as well in multi-monitor situations. It opens the first time. in second, third openings it doesn't.

If you wait long enough, roughly15 seconds, then click again later - it will eventually work. (Could this be related to the `DiscreteObjectKeyFrame's` `KeyTime` prop?

See the gif, you cannot just open-close-open-close.

![eartrumpet](https://user-images.githubusercontent.com/954596/156663481-7b0d518d-445a-4f6f-8e1e-00d5bdfef5f6.gif)

I looked at the FlyoutViewState enum, could it also be related to the fact that I do not use transitions, these are disabled for me)? I do also have multiple monitors as well, but again the strange thing is that it will eventually work later if I just leave it alone and wait. (I suspect the self-closing state is updating so its effectively 'reset')

Update: I just verified the behavior is the same, whether animations are enabled or not. Just can't open and close and reopen again. Gotta wait 15 seconds

**Comment by riverar** [comment] 2022-03-03 22:57
Thanks, this should already be fixed in dev builds. I haven't pushed out an update though, so that's my bad. Can you verify with a dev build? (You can click the link on the EarTrumpet homepage https://eartrumpet.dev.)

**Comment by the-simian** [comment] 2022-03-04 04:07
@riverar I installed it via scoop, I did notice there was a dev build via scoop.. should this be identical?

**Comment by tech189** [comment] 2022-03-12 00:48
@the-simian Scoop's `eartrumpet` package in Extras is the stable version, but there is no 'official' dev version - so no, it's not identical to the dev build on https://eartrumpet.dev/.

@Siphalor made a package for the dev build but it is out of date because their bucket's CI isn't working atm (I recommend they check out https://github.com/ScoopInstaller/BucketTemplate for an up-to-date GitHub Action setup for their bucket)

**Comment by Siphalor** [comment] 2022-03-13 08:31
> @Siphalor made a package for the dev build but it is out of date because their bucket's CI isn't working atm (I recommend they check out https://github.com/ScoopInstaller/BucketTemplate for an up-to-date GitHub Action setup for their bucket)

Ah, thanks for letting me know,  I fixed it so it's now delivering the latest dev version again :)

**Comment by riverar** [comment] 2022-04-07 22:04
This should be fixed in EarTrumpet 2.1.10 now available in the Microsoft Store, chocolatey, and other sources!

**Closed by riverar** 2022-04-07 22:04 UTC
Labels: status: fixed in next update
