### ISSUE TITLE
Test sound not playing when clicking slider heads

### ISSUE THREAD

**Issue by beppe9000** [File-New-Project/EarTrumpet#456] opened 2020-01-10 09:22 UTC
I think this should be replicated from windows behavior

**Comment by riverar** [comment] 2020-01-10 09:30
Thanks, closing as this is a duplicate of #425

**Closed by riverar** 2020-01-10 09:30 UTC

**Comment by beppe9000** [comment] 2020-01-10 09:36
Wow... lack of test sound everywhere had me thinking the feature was missing

**Comment by riverar** [comment] 2020-01-10 09:37
@beppe9000 It shouldn't be gone everywhere, it will play on the default device only. Which could be, say, Steam Streaming.

**Comment by beppe9000** [comment] 2020-01-11 13:14
That is what I was reporting
