### ISSUE TITLE
Feature request - make it moveable?

### ISSUE THREAD

**Issue by leerandall** [File-New-Project/EarTrumpet#117] opened 2017-04-13 19:12 UTC
Any chance you could make the mixer movable and pinnable, so I can keep it open and move it somewhere else on my screen like all of the previous Windows versions' mixers could be? It would make it quicker to be able to mute a particular sound source. Thanks for any consideration.

**Comment by riverar** [comment] 2017-04-13 19:18
This poses interesting challenges, like refreshing the window (live? polling?) without impacting the experience (pause when focused, perhaps?).

**Comment by riverar** [comment] 2017-04-13 19:19
Dupe of #115, thanks for the request.

**Closed by riverar** 2017-04-13 19:19 UTC
Labels: enhancement

**Comment by leerandall** [comment] 2017-04-13 19:41
Sorry about that, Raphael.
