### ISSUE TITLE
App is using ~1gb of storage for Data

### ISSUE THREAD

**Issue by randyramnansingh** [File-New-Project/EarTrumpet#358] opened 2019-05-09 05:54 UTC
Noticed in the Windows 10 App settings for ear trumpet that the app only uses 6.78 MB storage for the app itself but is using up to 1.03 GB for data storage, is this normal? 

![image](https://user-images.githubusercontent.com/14999360/57430316-46ccc400-71fd-11e9-88c0-a9573cd50fe7.png)

**Comment by riverar** [comment] 2019-05-09 10:50
Can you see anything eating up space in `%localappdata%\packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne`?

**Comment by randyramnansingh** [comment] 2019-05-14 07:04
actually yeah, `%localappdata%\packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\LocalCache` seems to be the main offender, `...\local\WhatsApp` is what is consuming most of the additional 1GB, seems to be storing the different versions of `Whatsapp.exe`

**Comment by riverar** [comment] 2019-05-14 07:34
@randyramnansingh Yeah this is a known issue with Windows. It's not really eating up 1GB, they're just links. You can jump in that folder and issue a `dir /al /s` to verify. As I've already confirmed Microsoft is aware of this, going to close this for now. If you see something awry, reopen/let us know!

**Closed by riverar** 2019-05-14 07:34 UTC
Labels: type: windows-bug

**Comment by jorticus** [comment] 2020-01-10 06:14
@riverar , I discovered something similar on my machine, but none of the files seem to be hardlinks (dir /al /s just says 'File not found')

They are consuming almost 1GB according to Explorer & Settings. Are you sure these are links?

Windows is 1903

**Comment by riverar** [comment] 2020-01-10 07:13
@jorticus Hm, that doesn't sound good. Are they current? All executables? This bug was supposed to be fixed with the new Centennial filter drivers in 19H1+.

**Comment by jorticus** [comment] 2020-01-10 07:19
Discord.exe & Riot.exe seem to be the offenders on my machine. Discord has 3 versions, latest copy is dated 2019-03-07. Riot has 11 versions, each roughly 80MB (yeah, it's another electron app), latest dated 2019-07-18.

So neither of these are current. Maybe they got left behind after the bug was fixed?
I suppose I could just delete them, but I'm worried the problem might be more widespread.

Thanks!

**Comment by riverar** [comment] 2020-01-10 07:37
@jorticus Yeah, my guess is you had pre-19H1 back until an upgrade that occurred somewhere around July 2019? You may be able to verify this via:
```powershell
PS> Get-ChildItem HKLM:\SYSTEM\Setup | Where-Object { $_.Name -like "*Source*" } | Select-Object name
```

There were actually two bugs in this area, both Desktop Bridge bugs. One involved reparse points (`fsutil reparsepoint query [filepath]`) getting created every time something like `GetFileAttributesExW ` got called. Another involved the Desktop Bridge touching PAGE_WRITECOPY mapped executables incorrectly resulting in an inadvertent copy occurring, straight into the LocalCache folder. (Not a bug is anything labeled NVIDIA. They love to inject helper code into everything and make a damn mess.)

**Comment by jorticus** [comment] 2020-01-14 04:21
@riverar yeah looks like I updated to 19H1 in August. That must have been a fun bug to find! 
I'll go ahead and delete the local cache since it sounds like these files won't disappear otherwise. 

Thanks for your help

**Comment by riverar** [comment] 2020-01-14 04:53
@jorticus Let's just say we are very... familiar with Desktop Bridge and the team. 😂 Thanks for double-checking with us, any other questions/troubles, please reach out.
