### ISSUE TITLE
Right-click menu appears the immediately disappears 

### ISSUE THREAD

**Issue by Aronjlove** [File-New-Project/EarTrumpet#422] opened 2019-09-30 01:21 UTC
While the extended mixer displays just fine when left-clicking on the EarTrumpet icon the right-click menu disappears immediately. I assumed it was related to my Windows Insider build but I encountered the same issue with a clean install of 1903. This happens on my home workstation with Nvidia video card but not my campus workstation with Intel built-in graphics, both 8th gen Intel chips. Other right-click menus in the tray work just fine.

![eartrumpet](https://user-images.githubusercontent.com/42818757/65843283-b2671900-e2e5-11e9-9ced-aa27ee9910d4.gif)

**Comment by riverar** [comment] 2019-10-11 17:38
Dupe of #399

**Closed by riverar** 2019-10-11 17:38 UTC

**Comment by riverar** [comment] 2019-10-11 17:41
Just heads up, this is fixed in our dev branch https://github.com/File-New-Project/EarTrumpet/commit/46c7bc983b5d31e3f6a0c0779da021375b043e3c will be in the next update. Thanks!
