### ISSUE TITLE
Hiding apps

### ISSUE THREAD

**Issue by Lukasz-egg** [File-New-Project/EarTrumpet#577] opened 2020-11-10 17:49 UTC
I have a problem. on apps list there is "dragon center" and "ledkeeper2", which are apps that I use but they dont giving any sound, can you add option to hide apps?

**Comment by kaovilai** [comment] 2020-11-10 18:11
Could be an option for advanced users. But I think it should be addressed directly in those apps. Why is it requesting to be a sound outputting applications in the first place?

Anyways dupe of https://github.com/File-New-Project/EarTrumpet/issues/263

**Comment by Lukasz-egg** [comment] 2020-11-10 18:33
These are system apps from motherboard, dragon center is main app, ledkeeper is extension-app that changes leds on motherboard, I dont know why their want to be sound outputting, but I cant do anything with that ://

**Comment by riverar** [comment] 2020-11-11 07:41
Close this as it's a dupe of another issue we're already tracking (#263).

**Closed by riverar** 2020-11-11 07:41 UTC
