### ISSUE TITLE
Displayfusion - Duplicate System Tray Integration

### ISSUE THREAD

**Issue by frsaba** [File-New-Project/EarTrumpet#446] opened 2019-12-07 16:18 UTC
I'm using Displayfusion 9.5 to duplicate my system tray onto my second monitor.
When I right click EarTrumpet on my secondary display,  it appears for a split second then closes immediately.
[Issue#1](https://i.imgur.com/Rx0m6GC.gifv)
When I left click to open up the volume mixer, the animation to open it plays on my primary display and once it finishes, the mixer appears and functions like normal on my second monitor.
[Issue#2](https://i.imgur.com/mv4DPRi.gifv)

**Comment by riverar** [comment] 2019-12-17 09:53
EarTrumpet does not expect the notification area to be in multiple locations. Marking this as a third-party bug simply because DisplayFusion introduced unexpected behavior breaking app compat. Could be something we address though, if deemed simple enough. Thanks for reporting!

**Comment by SullyvanLB** [comment] 2020-04-12 15:12
I have the exactly same problem !!! and with the original sound icon of windows 10, the issue 2 is the same but the 1 isn't there.

**Comment by tapr00t** [comment] 2020-07-27 23:45
Every other system try icon open the context menu on right click, on display fusion's other taskbars.  It's only ear trumpet that does not.

**Comment by Joshdw** [comment] 2022-01-17 11:35
Bumping this, it's still an issue 2 years later :(

**Comment by riverar** [comment] 2023-04-26 05:26
Apologies for taking so long on this one.

Tested this in DisplayFusion 10 and doesn't appear to be a problem. (It does briefly show on the first monitor but this appears to be a general DisplayFusion bug/design.)

![image](https://user-images.githubusercontent.com/475132/234477546-4ff3f4ca-522a-4cc7-b3c4-a1794283b21c.png)

Closing for now as it seems over time, the problem has gone away. Let me know if you see otherwise, what version of EarTrumpet/DisplayFusion you're on, etc.

**Closed by riverar** 2023-04-26 05:26 UTC
Labels: type: third-party-bug
