### ISSUE TITLE
Window moves very slow

### ISSUE THREAD

**Issue by Pretorer** [File-New-Project/EarTrumpet#436] opened 2019-11-03 00:21 UTC
If i move the main window with the mouse it moves very slow and it looks like the window record the input:
If i move the mouse fast by holding the left button, to move the window to a position (position the cursor must be but its icon is attached to the window so i can't see it) it moves a long time without input. Often it takes more as 10s to trevel 1000px. If i move the window with the arrowkeys and only holding the left mousebutton it moves as fast as every other program moving with arrowkeys.
While the window moves, other programs for example firefox with open youtube except a few games have frozen windows and blocked input and if i press the mousebutton one or two times, i see the real mouse icon as second mouse ( input is blocked often).
I use Winows10 Pro 1903 build 18362.418 but i have the problem since some month if it maters.

**Comment by designgears** [comment] 2019-11-03 07:14
Came to say the same, same version of windows as well.

I suspect it has to do with the mouse polling rate, office used to have a similar problem.

**Comment by riverar** [comment] 2019-11-03 07:18
Thanks, closing as this is a duplicate of #349. The API we use for Acrylic changed, we're working on a replacement.

**Closed by riverar** 2019-11-03 07:18 UTC

**Comment by moosenoises** [comment] 2019-11-12 22:14
I've used ear trumpet for awhile and just did a reinstall of windows and came across this problem for the first time. I was able to fix my issue by going to Advanced System settings>Settings under Performance>Adjust for Performance>OK

Hopefully this fixes it for others who still have the issue.
