### ISSUE TITLE
Eartrumpet flyout doesn't open when taskbar has auto-hide enabled and is on a secondary screen

### ISSUE THREAD

**Issue by Ameer2002** [File-New-Project/EarTrumpet#1207] opened 2022-08-18 10:33 UTC
### Summary

The flyout won't open via shortcut key if the taskbar is on a secondary screen and is currently hidden. If I hit the windows key to bring up the taskbar, then hit the shortcut key the flyout comes out. I tried leaving the volume mixer open in the background, but doesn't fix the issue. If I disable taskbar auto-hide the problem goes away, so it is related to auto-hide.

I tried re-installing eartrumpet, updating to the latest version but no change.

### Steps to reproduce

The taskbar needs to be on a secondary screen. 
Then enable taskbar auto-hide.
Then try to open the flyout via the shortcut key.

### EarTrumpet version

2.2.0.0

### Windows version

Win10 Pro 21H2 19044.1889

**Comment by riverar** [comment] 2022-09-05 20:47
Can't reproduce this on Windows 11 25193.1000. Could be a Windows 10 bug, investigating.

**Comment by Ameer2002** [comment] 2022-09-05 21:37
It's Ctrl+Shift+Q. I think I had tried rebinding to something else but the issue persisted.

**Comment by Ameer2002** [comment] 2022-09-05 21:51
I've just moved my taskbar to my 3rd monitor and tried this. I have the taskbar hidden, and not opened and sure enough the same shortcut binding works now. Really odd behaviour, I don't have HDR or anything like that enabled on the problematic monitor.

Sometimes, if I try the shortcut while the taskbar is hidden on the problematic monitor, it takes 3 or so presses of the shortcut to firstly bring up the taskbar, then to highlight the ear trumpet icon, then open the flyout. It does not do this on any other monitor. This doesn't always happen though, sometimes it flat out doesn't work at all.

**Comment by riverar** [comment] 2023-04-09 19:25
![image](https://user-images.githubusercontent.com/475132/230792545-65bebbc1-b646-4ede-9140-8b9070ebf70c.png)

Can't reproduce on Windows 10 22H2 19045.2728. Will close this for now but if it happens again, please let me know!

**Closed by riverar** 2023-04-09 19:25 UTC
Labels: status: can't reproduce
