### ISSUE TITLE
Icon is blurry at 113% scaling (DPI 108)

### ISSUE THREAD

**Issue by 1299897460** [File-New-Project/EarTrumpet#528] opened 2020-07-23 13:16 UTC
![image](https://user-images.githubusercontent.com/35516655/88290692-bc9d4c80-cd29-11ea-9186-04f96058afdd.png)

**Comment by riverar** [comment] 2020-07-28 21:04
Hey @1299897460 thanks for the heads up. We might be missing an icon size step. Please navigate to Settings > General > About and click Collect troubleshooting data. Copy and paste the top portion of the log (before the ---) into this issue.

**Comment by 1299897460** [comment] 2020-07-29 04:29
version: 2.1.7.0
runtimeMinutes: 2831
gdiObjects: 156
userObjects: 65
globalGdiObjects: 3893
globalUserObjects: 3893
handleCount: 1030
releaseStage: production
osVersionBuild: 19041.1.amd64fre.vb_release.191206-1406
osArchitecture: 64 bit
processorCount: 4 core(s)
IsLightTheme: True
IsSystemLightTheme: False
IsRTL: False
IsTransparencyEnabled: True
UseAccentColor: True
AnimationsEnabled: True
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False
Culture: zh-CN
CurrentUICulture: zh-CN
systemDpi: 108
taskbarDpi: 108
addons: 
region: CN

**Comment by 1299897460** [comment] 2020-07-29 04:29
> 嘿@ 1299897460感谢您的注意。我们可能缺少图标尺寸步骤。请导航至“设置”>“常规”>“关于”，然后单击“收集故障排除数据”。将日志的顶部（-之前）复制并粘贴到此问题中。

version: 2.1.7.0
runtimeMinutes: 2831
gdiObjects: 156
userObjects: 65
globalGdiObjects: 3893
globalUserObjects: 3893
handleCount: 1030
releaseStage: production
osVersionBuild: 19041.1.amd64fre.vb_release.191206-1406
osArchitecture: 64 bit
processorCount: 4 core(s)
IsLightTheme: True
IsSystemLightTheme: False
IsRTL: False
IsTransparencyEnabled: True
UseAccentColor: True
AnimationsEnabled: True
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False
Culture: zh-CN
CurrentUICulture: zh-CN
systemDpi: 108
taskbarDpi: 108
addons: 
region: CN

**Comment by riverar** [comment] 2020-07-29 04:45
Thanks. Sounds like you have a custom scale set to *112.5%*, can you verify? You can find this value in Settings > System > Display > Advanced scaling settings.

![image](https://user-images.githubusercontent.com/475132/88757742-94dc2900-d11b-11ea-87be-c8174a403ea1.png)

Related #495.

**Comment by 1299897460** [comment] 2020-07-29 05:02
> 谢谢@ 1299897460。您的自定义比例似乎设置为**112.5％**，对吗？您可以在“设置”>“系统”>“显示”>“高级缩放设置”中找到该值。
> 
> ![图片](https://user-images.githubusercontent.com/475132/88757862-e2f12c80-d11b-11ea-96f9-9ffc03beb983.png)
> 
> 相关[＃495](https://github.com/File-New-Project/EarTrumpet/issues/495)。
![image](https://user-images.githubusercontent.com/35516655/88758665-8cc3ce00-d19b-11ea-8b55-e78d46f76965.png)

**Comment by davuxcom** [comment] 2021-02-18 03:20
Unsupported size, need to use a more common size. We would have to pack more and more specific assets to deal with this and that's not really workable.

**Comment by davuxcom** [comment] 2021-02-21 00:26
Dupe of https://github.com/File-New-Project/EarTrumpet/issues/495

**Closed by davuxcom** 2021-02-21 00:26 UTC
Labels: type: bug
