### ISSUE TITLE
app icon is not showing

### ISSUE THREAD

**Issue by RakibPro** [File-New-Project/EarTrumpet#1086] opened 2022-03-11 11:36 UTC
### Summary

Spotify app icon is not showing

### Steps to reproduce

fix this problem

### EarTrumpet version

EarTrumpet Version : 2.1.9.0

### Windows version

Windows Version : 10.0.19044.1586

### Additional information

![EarTrumpet_Bug](https://user-images.githubusercontent.com/71222636/157859400-222c1242-eefd-4457-a652-610cf3a77c87.png)

**Comment by riverar** [comment] 2022-03-16 21:18
Closing this issue as there's not enough information provided and I can't reproduce it. Feel free to provide more info / re-open!

**Closed by riverar** 2022-03-16 21:18 UTC

**Comment by cbouju** [comment] 2023-04-19 15:45
I have a problem matching the description in this thread:

When Windows (10) starts, the EarTrumpet icon does not appear in the notification bar.
To make it appear, I have to launch the application from the start menu.

Also, the native Windows sound management icon remains visible all the time :  when Windows starts, and when I launch EarTrumpet from the start menu.

This problem occurs for both the standard and dev versions of EaarTrumpet.
