### ISSUE TITLE
Glitchy/Laggy Window when moved around desktop

### ISSUE THREAD

**Issue by dboling19** [File-New-Project/EarTrumpet#541] opened 2020-08-14 00:31 UTC
When using the pop-out window option (which is the main reason I'm using this system), everything works great except moving the window around to adjust where it sits on my screen, or moving it out of the way. I know everything else on my system works perfectly fine (besides Office 365 windows for some reason; connected issue?). Not a major issue obviously, just didn't see it listed already when looking for a possible current-issue/fix.

**Comment by riverar** [comment] 2020-08-14 06:44
Thanks, this is a dupe of #349.

**Closed by riverar** 2020-08-14 06:44 UTC
