### ISSUE TITLE
Windows 10 - Update 1903 - Lagging Window movement

### ISSUE THREAD

**Issue by OtterNas3** [File-New-Project/EarTrumpet#386] opened 2019-06-15 10:14 UTC
After updating to Windows 10 version 1903, when you try to move the EarTrumpet Window, it locks the Mouse to the window and starts moving very very slowly until it reached the position where you "tried" to move it. You cant abort and have to wait until the movement is finished.
And if you grab the window and then move your mose left and righ a few times very fast, it lags behind and takes sometimes minutes to finish the move.
You cant do nothing with your mouse when this happens, it gets stuck to the window itself.

Moving Sliders, App Icons, all good, just the moving of the window is weird.

**Comment by davuxcom** [comment] 2019-06-15 13:08
Thanks, this is a known Windows bug and a dupe of #349.

**Closed by davuxcom** 2019-06-15 13:08 UTC
