### ISSUE TITLE
system / program volume too low issue

### ISSUE THREAD

**Issue by milkyjoe2** [File-New-Project/EarTrumpet#464] opened 2020-02-20 00:13 UTC
this is a commonly occurring problem which i formerly ascribed to windows which i have just diagnosed as being an ear trumpet issue.

the issue: low volume in windows. 

if i use ear trumpet to lower the volume of just one program, like itunes, yes it lowers the program's volume but when i later go to restore the volume up to full, 100, the actual volume is not really restored to 100 and remains low. for a long time i couldn't understand why my music sounded so quiet unless i rebooted pc. i'm 75% sure it's ear trumpet causing this issue.

**Comment by riverar** [comment] 2020-05-07 09:13
@milkyjoe2 Thanks, does this happen with all programs or just iTunes?

**Comment by milkyjoe2** [comment] 2020-05-07 15:48
More than just iTunes, chrome for example

On 7 May 2020, at 10:13, Rafael Rivera <notifications@github.com> wrote:

﻿

@milkyjoe2<https://github.com/milkyjoe2> Thanks, does this happen with all programs or just iTunes?

**Comment by riverar** [comment] 2021-02-24 08:26
Closing. We can't reproduce this (sorry @milkyjoe2!). Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. Thanks!

**Closed by riverar** 2021-02-24 08:26 UTC
Labels: status: can't reproduce
