### ISSUE TITLE
Some improments needed

### ISSUE THREAD

**Issue by PIndividual** [File-New-Project/EarTrumpet#555] opened 2020-08-27 10:47 UTC
I wish there could be a function where I can choose to hide some app from being displayed on the ear trumpet application ,and to can also re-enable them in the ear trumpet seetings ,because some of the apps I really don't need to adjust them ,but they keep showing up which is kind of annoying

**Comment by riverar** [comment] 2020-08-27 16:41
Thanks, this is a duplicate of #263

**Closed by riverar** 2020-08-27 16:41 UTC
