### ISSUE TITLE
It's hard to drag Windows

### ISSUE THREAD

**Issue by yinyue200** [File-New-Project/EarTrumpet#379] opened 2019-06-07 15:37 UTC
OS: Windows 10 1903 (18362.145)

It seem that Volume Mixer Window has bad performance in dragging even if the PC has enough CPU time.

The problem should not be caused by the wireless mouse, because I dragged the calculator window without delay in the video, and a wired mouse can still reproduce the problem.

Video: https://drive.google.com/file/d/1-NkMLTnt-MeNU3SrcbNRTSW4_1bp5kxH/view?usp=sharing

CPU status during the video:
![TIM图片20190607233444](https://user-images.githubusercontent.com/13848771/59115910-de4c4080-897c-11e9-8012-29f8161a9816.png)

**Comment by yinyue200** [comment] 2019-06-07 15:50
Setting Window has same problem.

**Comment by riverar** [comment] 2019-06-07 19:26
Thanks, this is a known Windows bug and a dupe of #349.

**Closed by riverar** 2019-06-07 19:26 UTC
