### ISSUE TITLE
Changing Soundcloud volume doesn't work

### ISSUE THREAD

**Issue by ChristoferMinestar** [File-New-Project/EarTrumpet#178] opened 2018-01-08 18:55 UTC
Since SoundCloud uses a weird system for playing music (has 2 sliders in EarTrumpet that only change bass and treble not volume) it doesn't work with SoundCloud, but it *might* a SoundCloud bug because SoundCloud for Windows 10 is in beta.

**Comment by riverar** [comment] 2018-04-08 19:35
Can you still reproduce this @ChristoferMinestar ?

**Comment by riverar** [comment] 2018-04-25 03:28
![soundcloud](https://user-images.githubusercontent.com/475132/39224831-03e18e98-47fe-11e8-8e92-59c79c210024.gif)

This is insane. Reaching out to SoundCloud.

**Comment by riverar** [comment] 2018-06-13 06:12
SoundCloud refuses to communicate with me, and this bug *still* exists.

**Comment by ChristoferMinestar** [comment] 2018-06-21 20:08
Still known bug... Have they tried fixing this or even responded yet? I switched to a JS wrapper over the website just to use it individually, and they app is great.

**Comment by riverar** [comment] 2018-06-21 20:21
SoundCloud hasn't responded at all. I don't know how to reach anyone there.

**Comment by GoldenTao** [comment] 2018-10-14 00:55
Duplicate of #146

**Closed by GoldenTao** 2018-10-14 00:55 UTC
Labels: type: third-party-bug
