### ISSUE TITLE
Per device mute settings broken on 24H2

### ISSUE THREAD

**Issue by Chetan-Ullal** [File-New-Project/EarTrumpet#1645] opened 2024-12-09 15:38 UTC
### Summary

I recently got a new laptop that came with 24H2. On earlier versions of Windows, when the bluetooth headphones were turned on, audio would switch to the headphones, and be unmuted. When turned off, the audio would switch back to the laptop and be muted. This no longer happens. When the headphones connect, audio is still muted, and I have to unmute it manually.

### Steps to reproduce

- Mute the audio on the laptop.
- Connect bluetooth headphones
- Unmute the headphones audio (by clicking the speaker icon in the EarTrumpet flyout)
- Disconnect the bluetooth headphones
- Notice the laptop has audio muted
- Re-connect bluetooth headphones
- Notice that audio has switched to the headphones, but it's still muted.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.26100.2033

### Additional information

This happens on 24H2 with the October update applied. For various reasons, I tried installing 23H2 on the laptop (which had other issues, thus turned out to not be viable). However, during that time I tested the same scenario as above, and the bug above did not manifest. I'm fairly certain this has something to do with the 24H2 update.

**Comment by riverar** [comment] 2024-12-11 17:52
Yep, you're not alone. 24H2 is shaping up to be quite the buggy release.

* https://answers.microsoft.com/en-us/windows/forum/all/after-windows-11-24h2-microphone-keeps-unmuting/7dde34f4-a99b-4be0-b313-97c5ba943e5d
* https://answers.microsoft.com/en-us/windows/forum/all/g-pro-x-wireless-plays-muteunmute-sound-when-audio/985f5be6-3596-40a9-a62b-a2df771ccc41

One suggestion is to try a dev build (https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller) and set up an EarTrumpet Action to unmute the default playback device when the default changes. Something like this:

![image](https://github.com/user-attachments/assets/ee2aada6-295a-45ed-a0b9-012f76aef80b)

**Comment by riverar** [comment] 2024-12-11 17:53
Going to close this for now as there's no work to be done, but feel free to keep the discussion going. (Am curious if the action helps you!)

**Closed by riverar** 2024-12-11 17:53 UTC
Labels: type: windows-bug

**Comment by Chetan-Ullal** [comment] 2024-12-11 22:36
@riverar I tried the following:
- Your settings exactly as above, didn't work at all
- I tried setting it so it unmuted the headphones when it became the default, and with that I can see it flash to unmute before it gets muted again, so progress? :)

Also, an annoying thing is that every time I open this actions panel via the context menu, a new empty action is added, which I have to keep deleting.

**Comment by Chetan-Ullal** [comment] 2024-12-11 23:11
@riverar Please let me know if you want me to try something else. Thanks.

**Comment by riverar** [comment] 2024-12-11 23:46
If it helps, I tested this with Windows Insider Build 27758 and cannot reproduce, so a fix for retail builds might be coming soon?

**Comment by Chetan-Ullal** [comment] 2024-12-12 00:47
That's good to know. In the release notes for that build I see:
"Fixed an underlying issue which could lead you to unexpectedly hear a mute or unmute noise in certain headsets". 
This looks like a fix to the issue you linked earlier, which might have fixed this issue too?

**Comment by riverar** [comment] 2024-12-12 00:58
I can't reproduce this on Windows Insider 26120.2415 either, so an OS fix for retail builds might ship soon. I'll try to reproduce this on a vanilla Windows 11 machine and determine if there's anything we can do here to help you in the meantime.

Regarding the empty action--yeah I see that here too, annoying. Will fix that.

**Comment by riverar** [comment] 2024-12-12 20:10
@Chetan-Ullal I reached out to the Windows Audio team and they're asking for an audio subsystem trace. The easiest way to facilitate this is by creating an issue in Feedback Hub under `Devices and Drivers > Audio and sound`. Under Attachments > Recreate my problem, click Start Recording and go through your repro steps. After submitting it, please share a Feedback Hub link here and I'll pass it on. Thanks in advance!

**Comment by Chetan-Ullal** [comment] 2024-12-13 15:21
@riverar I submitted the report, but since I don't have MS sign in on that machine, I didn't get a link.
Maybe the title of the report might be of use? It was "EarTrumpet: Per device mute settings broken on 24H2"

**Comment by riverar** [comment] 2024-12-13 20:42
Not seeing feedback with that title in FBH. I checked with Microsoft and they can't find it either.

**Comment by Chetan-Ullal** [comment] 2024-12-13 23:15
That is unfortunate. Can I submit it some other way? I didn't get any errors from the FBH app, so I assumed it had been submitted.

**Comment by Chetan-Ullal** [comment] 2024-12-25 18:02
@riverar following up to see if I can still help in fixing this issue. thanks.
