### ISSUE TITLE
Indication bar doesn't go to 0 when silent

### ISSUE THREAD

**Issue by ghost** [File-New-Project/EarTrumpet#837] opened 2021-05-19 11:03 UTC
## Description
When you play a sound through 2 applications (in this case a music player and Microsoft Teams) and then silence one of the two (a person speaking on Teams for example), the indication bar of it will move exactly the same as the other (the music player for example).

## Steps to reproduce (I think, it might require other steps)
1. Open two apps that play audio
2. Start playing audio through both
3. Open the EarTrumpet mixer (with the tray icon)
4. Pause one of the two applications (using a media keyboard)
5. See error

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19043.985 (OS independent)

**Comment by BennoMP** [comment] 2021-05-27 09:08
![image](https://user-images.githubusercontent.com/61586142/119798796-c066a600-bedb-11eb-82be-b519745174ce.png)
Here's a screenshot, I doubt the person talking on Teams speaks with the exact volumes per channel as the music I'm playing on Edge

**Comment by riverar** [comment] 2024-11-13 01:33
Closing as unable to reproduce. If you run into this again, please let us know.

**Closed by riverar** 2024-11-13 01:33 UTC
Labels: status: can't reproduce
