### ISSUE TITLE
Windows App Store 1.4.2 BSOD

### ISSUE THREAD

**Issue by prawksee** [File-New-Project/EarTrumpet#84] opened 2016-09-27 13:21 UTC
I'm getting BSOD everytime I try launching the application from the windows app store. The desktop client 1.3.2 works just fine but currently only the source files exist for 1.4+. I need 1.4.2 for Forza Horizon 3. Please help

**Comment by Fawad95** [comment] 2016-09-27 13:56
Experiencing the same here(1.3.2 works with no problems). Have had 10 bsod so far. Just having the app installed (not launched after initial bsod) will bsod.
It says KERNEL SECURITY CHECK FAILURE when it bsods.
Used bluescreenviewer to make these htmls out of the dumps.
http://pastebin.com/iaAG5292
http://pastebin.com/gaBa3ZYF
Just save as html.

**Comment by riverar** [comment] 2016-09-27 16:02
Yikes, can you folks locate the crash .dmp files and send us a copy? If you need a storage location, ping me via email (rafael@withinwindows.com) and I'll send you a OneDrive folder to upload to.

**Comment by riverar** [comment] 2016-09-27 20:19
Also tracking a report at Ten Forums http://www.tenforums.com/bsod-crashes-debugging/65153-bsod-when-opening-specific-windows-store-app-eartrumpet.html?posted=1#post825339

**Comment by riverar** [comment] 2016-09-27 20:28
Microsoft: "There was a bug in an opengl driver that was exposed by Centennial. The fix is going out soon."

**Comment by riverar** [comment] 2016-09-28 16:15
Right now, Microsoft. But if would like to capture a complete memory dump for us, that'd be extremely helpful at determining if we can workaround it.

**Comment by GoldenTao** [comment] 2016-10-08 07:56
This one looks to be fixed in the latest Windows Insiders Fast Ring Build 14942.  Not sure when this will go out to Slow Ring or those not on Insider builds yet.

**Comment by fever974** [comment] 2016-10-11 19:09
Hello i have the same problem like many people. I do 10/11/2016 windows update and actually no change about this bsod :( i hope that wasn't their supposed update ..

**Comment by riverar** [comment] 2016-10-11 20:52
As @GoldenTao said, this is only fixed in Fast Ring builds. There is no update being delivered WU at this time. Maybe closer to the end of the month.

**Comment by McNippleson** [comment] 2016-10-20 05:37
I think you should update it and make it not put itself into autostart by default. I've installed it and moved the files yet I kept getting BSODs after booting until I remembered I have eartrumpet installed. Never expected it to be running by itself.

**Comment by redion1992** [comment] 2016-10-28 14:27
Update is out. https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-known-issues

**Comment by riverar** [comment] 2016-10-28 16:17
Thanks, we're making the necessary changes.

**Comment by ksiazkowicz** [comment] 2016-11-22 01:10
I'm still getting that on 14393.447.

**Comment by riverar** [comment] 2016-11-22 01:37
Hi @ksiazkowicz, can you elaborate as to what you're experiencing? Are we talking the same exact STOP error code? Can you provide a crash minidump and/or event logs?

**Comment by ksiazkowicz** [comment] 2016-11-22 01:46
In my case it's a random BSOD (KERNEL_SECURITY_CHECK) that occurs once a week. According to WinDBG bugcheck analysis, it's caused by EarTrumpet as well. I'll mail you these in a few hours.

**Comment by TPdeC** [comment] 2017-02-02 16:57
I'm getting that on 14393.693 
Every few days (14 times since 19/12/2016), on resume from standby.
Full memory.dmp available.

**Comment by riverar** [comment] 2017-02-02 18:06
Can you provide that (privately) for analysis? You can reach me at <rafael@withinwindows.com>.

**Comment by GoldenTao** [comment] 2017-12-21 07:59
If anyone is still having this problem, please reopen this issue.

**Closed by GoldenTao** 2017-12-21 07:59 UTC
Labels: windows-bug
