### ISSUE TITLE
Feature Request: let EarTrumpet save it's settings

### ISSUE THREAD

**Issue by Droyk** [File-New-Project/EarTrumpet#98] opened 2016-12-18 15:14 UTC
Good evening Developers,
I want a feature from you guys to make my life a little easier let EarTrumpet save it's settings I don't know why you guys didn't implement this yet but plz add it so I can live my life a little easier 

**Everytime I shutdown or restart or signout of my computer ear trumpet forgets everything plz do something about it!!**

**Comment by Shadesss** [comment] 2017-01-06 01:19
+1

**Comment by riverar** [comment] 2017-01-06 04:03
This is tough because Windows itself doesn't support it. Will investigate as this is a common request.

**Comment by Droyk** [comment] 2017-01-06 12:39
>Will investigate

really 😞😢 I have been hearing that word for a while... and it only seem to me as an excuse as I said on my previous issue it's been 6 months since last ear trumpet update and there is doesn't seem to be any working on ear trumpet at all. 

tell me how hard it is to implement a saving feature I have seen many UWP apps that save my history, passwords, etc and you can't implement a single saving feature!!

**Comment by riverar** [comment] 2017-01-07 04:37
Funny.

Just to be clear -- Are you talking about saving volume levels per app?

**Comment by Droyk** [comment] 2017-01-07 10:26
>Funny.

No it isn't I like ear trumpet but I want it to have some good features.

>Are you talking about saving volume levels per app?

yup 😤>:(

**Comment by Droyk** [comment] 2017-01-10 20:31
you didn't reply me @riverar plz tell me when you guys going to work on the next update to add this feature

**Comment by riverar** [comment] 2017-01-10 20:41
I'm not convinced this feature makes sense to implement. Can you explain in detail why you want this? Do you often start apps that you want at a specific volume? Why?

**Comment by Droyk** [comment] 2017-01-10 21:08
>I'm not convinced this feature makes sense to implement.

@riverar now it seems like you are trolling with me and now you are making yourself really stupid.

>I'm not convinced this feature makes sense to implement.

really ask any sensible person they will tell you really easily why this feature is important. 

I will give you a simple answer it make's my life really easy doesn't let me waste my time on muting some apps sounds and changing some apps sound level everytime I restart my computer.

Okay let me give you the same question why do you use bookmark feature in your browser? it doesn't make any sense to bookmark something when a user can easily type it on addressbar. Can you explain in detail why do you use it? Do you often go to those sites if yes then why can't you just pin them? Why? Why? Why?

the answer is simple a user want's to open them without wasting their time on writing the whole URL in the address bar that's the reason they created a bookmark feature that let them open the webpage effortlessly without wasting their time on learning the whole url, writing the url.

Here is another question for you Why do use saving feature in any application at all you just have to remember it right can't you just do that Can you explain in detail why do use a pesky saving feature at all?  Why? Why? Why?

**Comment by riverar** [comment] 2017-01-10 22:10
What apps are you muting **after a restart**? What apps are you changing the volume of **after a restart**? I'm trying to understand the way you use EarTrumpet.

Keep in mind Windows does not guarantee a start-up order for UWP apps. The apps that you want to restore volume settings for could start before EarTrumpet. This is just one of the many facets of the problem that you may not have considered. It's a complex issue.

**Comment by stevek123** [comment] 2017-01-10 22:19
I think it's the same issue as #23 #31 #88 

For example, in #88, there is no way to mute the audio in the game itself, and it start pretty loudly.

The boot order can be a limitation, but I think it's still beter if the audio is on for a few seconds for an app, then not having this feature at all.

I also miss this feature, because there are some system sounds (like notification sounds) that you can't mute in the old mixer, but you can mute in EarTrumpet, but the app keeps forgetting it on every restart.

**Comment by riverar** [comment] 2017-01-10 22:25
Thanks @stevek123. Am I missing something?

Solitaire has audio controls here.
![image](https://cloud.githubusercontent.com/assets/475132/21827425/5d70edf8-d740-11e6-9802-15deb2fe2734.png)

And various system sounds, like the one tied to Notifications, can be turned off via 
![image](https://cloud.githubusercontent.com/assets/475132/21827473/978bc3fa-d740-11e6-9da6-cb2efed84235.png)

**Comment by Droyk** [comment] 2017-01-10 22:30
>What apps are you muting after a restart? What apps are you changing the volume of after a restart?

As @stevek123 said Default one is windows notification in your ear trumpet tooltip says it is system sound and shell notification sound and then come's some of my media players 

>Keep in mind Windows does not guarantee a start-up order for UWP apps. This is just one of the many facets of the problem that you may not have considered. It's a complex issue.

you just said above that "it's not trivial but can be done." so plz do it I understand the start up order issue as @steve123 said "but I think it's still better if the audio is on for a few seconds for an app, then not having this feature at all."

@riverar 
yes you can disable those notification sounds but sometimes I want to hear notification sound so I just want simple toggle through ear trumpet on 60% of cases I don't want to hear notification sound but on those 30% of cases I want to enable sound via ear trumpet.

**Comment by stevek123** [comment] 2017-01-10 22:33
I don't remember having that option in the game before, I think they have updated it since then (or I was the one who wasn't able to find it :D Now it's definitely there for me too, so thx for the info). 

About the notifications: You are right, it's a workaround (if you want to turn of completely), but not necessarily a solution.

**Comment by Droyk** [comment] 2017-01-10 22:35
Yup it is just a workaround not a permanent solution.

**Comment by Droyk** [comment] 2017-01-11 13:10
And your response @riverar

**Comment by Droyk** [comment] 2017-01-15 00:18
@riverar

**Comment by phred73** [comment] 2017-01-18 14:41
I'd like to request this feature also. As for now, when I start an app it starts with 100% volume. If note possible to save per app maybe setting a default start volume instead (not 100%) of new apps?

**Comment by riverar** [comment] 2017-02-13 06:46
Windows 10 Creator's Update supports saving app volumes now, so this isn't a feature we need to implement. I tested on 15031.rs2_release.

**Comment by Droyk** [comment] 2017-02-13 07:03
>so this isn't a feature we need to implement.

oh really don't lie you won't even add it 
even if it wasn't supported in the creator update.

**Comment by moraks** [comment] 2017-08-08 16:58
ET 1.4.4.0, win 10  v15063. Volume Level for " Windows Shell Experience Host" not saved. I'm install EarTrumpet special for control new system notification volume level. But it not work... I'm setup 5% of Volume for " Windows Shell Experience Host" , after 5 min it 100% again - terrify!

**Comment by stevek123** [comment] 2017-09-22 01:34
@riverar I'm experiencing the same thing as @moraks. It won't save the mute

**Comment by moraks** [comment] 2017-12-08 13:56
The problem is also relevant for the new version. "Windows Shell Experience Host" always returns to 100%

**Comment by minimashor** [comment] 2018-02-07 23:09
@riverar In response to your inquiry about the way I use EarTrumpet, I use it as a mixing board like in a recording studio. I would really appreciate having the ability to set a volume level for each application that would persist after a restart. Not every program has the ability to adjust volume levels, and I would really like to have all of my level sliders in the same place. I would love to help and answer any questions about my usage patterns.
Thanks,
Adam

**Comment by Striferx84** [comment] 2018-06-16 07:49
Reporting the same issue. I installed latest version of EarTrumpet a couple days ago, to help manage audio levels.

I use a headset, and having my audio levels boost to 100% is not ideal. So I keep the volume of my headset device master volume set at 100%.

I then adjust the volume settings for each individual application, as some applications I want only on 5% volume, or lower; such as notification and alert sounds. Other audio application sounds I keep at 25%, or whatever is comfortable.

As a user mentioned above among several others, once your PC auto-locks/signs out/restarts, all the audio levels reset to the max set "Master volume level" of the device. This is unacceptable, as it is a problem for headset users, and is potentially harmful.

I'm using Windows 10 Home, version 1803, OS Build 17134.112

Is there any update or fix to this problem?

**Comment by moraks** [comment] 2018-06-26 07:05
@Striferx84  "volume set at 100% for some WinApp"  is a windows bug, but microsoft persistently ignore this... Please, write new bug's report to Microsoft, may be someday they will notice it. I wrote about this problem three times already😂

**Comment by Skcyte** [comment] 2018-06-28 17:14
I can relate to Striferx84's problem. Everytime there's an app update whether it's windows app or other app it will reset the max volume. I hope there's a solution to this, being to able save the app name instead reset every newer executable is a life saver.

**Comment by ScientificNerd** [comment] 2018-08-13 08:03
I am not having problems with saving levels on reboot, bar one.  Windows Shell Experience Host always comes up at 100%.  This blasts me out of my seat when a Windows Notification pops up.  Your app is great, but being able to maintain levels of the Shell Experience Host on boot/reboot would be invaluable for me.  Especially since the icon doesn't show up anywhere until it blasts me out of my seat, and never shows up on the Windows mixer, which is why I found EarTrumpet.

If this is strictly a windows only issue, and there's nothing you can do about it, I totally understand.  MS doesn't appear to respond to issues very much though, so I don't expect it will ever be fixed.

**Comment by BlueArcherX** [comment] 2018-11-14 03:36
> I also would like to see this be implemented as well. I currently have my volume up pretty high and set the rest of my programs to low volume except for my music player. I also have some alarms on my computer so it gets a bit annoying when they go off really loud since EarTrumpet does not save the Windows Shell Experience volume. Of course, I could just rethink my strategy on handling volume for all my programs and music but prefer not to since I have other speakers around me not independent of my computer's volume so I have to match everything up. Also, unfortunately, there is no way to modify the volume specifically for my alarm app and I don't want to have to look for another alarm app because of this since the alarm app I like is pretty good (with the exception you cannot control the volume individually)

I am with you, but I think the WIndows Shell Experience issue is a Windows one not an EarTrumpet one. 

I really hate it though.

**Comment by ender4** [comment] 2018-11-24 06:33
I would also like to request this feature. I found this app by searching for the Windows Shell Experience Host volume issue.

**Comment by tjsepka** [comment] 2019-02-24 08:09
Same issue / problem here.  I also see it with Firefox (FF) tabs.  With FF, usually only one control returns to its previous level and all others are set to Volume Mixer's Device (a.k.a., "output volume") slider level.  The system notification level control (**not the System Sounds application slider on the Volume Mixer!!!**) _always_ (as far as I can remember), is set to the Volume Mixer's Device's level.

It's not unusual in pro-audio applications to set the power amplifier's level control (if it has one at all!) to maximum and control all audio levels from the mixing board.  I'm an Electrical Engineer and used to design pro-audio equipment used in churches, school auditoriums, stadiums, theaters, and other large venues, and our power amp had screwdriver-adjust trim pots, only because we didn't always have knowledgeable pro's using Pro equipment, and they were used to having volume pots.  So setting Windows device level to maximum had been my approach when using Window's Mixer.  Bad news when you drop in a CD and Window's notification blasts at you asking you what to do with it...

Anyway, I don't have a solution, but I'm looking at NirSoft's "SoundVolumeView" and "AppAudioConfig" capabilities (when I have time) and would ask others with this issue have a look, too.

I always welcome helpful and useful comments and suggestions!

**Comment by riverar** [comment] 2019-02-24 08:17
Hey everyone, this is supposed to be supported by Windows but agree, it's broken. I'm working with Microsoft on this. In the meantime, we also have an EarTrumpet add-on in the works that will give you the ability to set volumes per app when they start, end, etc. Bear with us, we're close. Thanks!

**Comment by tjsepka** [comment] 2019-02-24 14:52
Thank you for the update, riverar.  That's great news!

Once that's fixed, it would be nice to have EarTrumpet implement the classic Windows mixer layout as an option, one which adds minimize and restore functions, as well as being fully resizable.  I use a dual monitor setup and dock Windows mixer in the lower right hand corner of my secondary right hand monitor, with my left hand monitor being my primary.

**Comment by Rocketboy235** [comment] 2019-02-24 15:43
Thanks Rafael! Really appreciate you following up and also putting the hard work into making this.

**Comment by riverar** [comment] 2019-02-24 20:31
> Once that's fixed, it would be nice to have EarTrumpet implement the classic Windows mixer layout as an option, [...]

Heads up, we do have a volume mixer very similar to the classic one. Or were you looking for something else? ![image](https://user-images.githubusercontent.com/475132/53304943-04b3f900-3830-11e9-88cb-e58490036210.png)

**Comment by tjsepka** [comment] 2019-02-24 23:08
For the life of me, I can't find the GUI you show above!  Can you advise me as to what I'm doing wrong?

**Comment by riverar** [comment] 2019-02-24 23:10
@tjsepka If you right-click the EarTrumpet icon in the notification area, you get this context menu 
![image](https://user-images.githubusercontent.com/475132/53306765-43ed4480-3846-11e9-8c55-05c6d8b0923c.png)

Click EarTrumpet Volume Mixer 👍

**Comment by tjsepka** [comment] 2019-02-25 00:56
Got it!  I ran across that screen, but didn't look closely enough at it.  My impressions are:

1.) The screen cannot be minimized;
2.) The screen cannot be resized.  It takes up considerable area of my monitor;
3.) The peak indicators only show significant deflection (levels) when the control is turned up quite high.  This might be occurring if the transfer function being used is linear rather than logarithmic (also known as "audio tapered"}.
4.) It would be nice if each channel's level indicator had its own color.

**Comment by factormystic** [comment] 2019-04-25 14:50
> Windows 10 Creator's Update supports saving app volumes now, so this isn't a feature we need to implement. I tested on 15031.rs2_release.

Is this a standard windows feature, or a new API exposed to apps to save/restore their own volume levels? I've noticed that closing/reopening a uwp app will cause its volume to reset to 100%, but I can't tell if this is what is being discussed in this thread (not really about rebooting, and not sure if it's an eartrumpet thing or not).

**Comment by riverar** [comment] 2019-04-26 21:34
@factormystic It's supposed to Just Work ™️ with no exposed API. But we haven't seen it work at all these days, suspect it's broken. Please also file a Feedback Hub issue and link me so I have the ammunition to push back on Microsoft in our thread. Thanks!

**Comment by Testi89** [comment] 2019-05-15 14:53
Saving the volume setting would be great. I use TuneIn Radio app with a headset, and I always have to correct from 100 to 1 not to get blown away. 
I use Windows 10, 1709, build 16299.1087

**Comment by PaddyMcQ** [comment] 2019-07-12 06:20
This was a painful thread to read.  Anyway, I installed Ear Trumpet specifically to normalize volume levels between Microsoft Edge browsing sessiona and my local apps.  Sampling music on various websites using Edge, the volume is always twice as loud as my local music player.  I cannot adjust my master volume and/or player volume to compensate.  Ear Trumpet works great and fixes this but... the volume level set in Ear Trumpet are not saved when I reboot.  Thanks.

**Comment by sagegriesfox** [comment] 2019-07-25 19:06
Having EarTrumpet create a Persistent App volume is the SINGLE MOST VALUABLE feature I feel you could ever add.  Indeed it was the reason I installed EarTrumpet !  I have a whole-home music system and home automation center than controls our background music 24/7 as well as home environmental conditions.
The system (running Win 10) regularly reboots itself to manage software updates as well as general house-cleaning.  Every time it reboots all of the dings, dongs, beeps, and bleeps that the system and various App create (to the annoyance of home music listeners) become loud again and I have to manually reset them to a level of 5% so they can be heard but not heard.

How hard can it be, no matter what order Apps are loaded, to store settings in the Registry and then examine and correct things as needed 30 seconds after EarTrumpet starts up and things have stabilized?

PLEASE, PLEASE, PLEASE, PLEASE, PLEASE do this as it is badly needed and you will be the ONLY one in the whole world that solves this issue!

 [:-)>

**Comment by tjsepka** [comment] 2019-07-25 21:38
I agree & I feel your pain
!

**Comment by mgutt** [comment] 2019-07-31 23:05
I thought EarTrumpet could solve my problem but with this "bug" its not a real fix.

Finally I solved it by reducing the volume of all Windows Notification WAV-files. If you speak German or able to use a translator you can follow this How-To:
https://www.maxrev.de/plex-ist-zu-leise-oder-windows-benachrichtigungen-sind-zu-laut-t394161.htm

**Comment by drawbars** [comment] 2019-08-02 02:15
Let me add another example of why saving the volume for applications is closer to a deal-breaker than a nice-to-have ...

I'm a musician.  I tend to keep my Windows system prompts, browser, etc. at a moderate level; let's call it 30 (out of 100) for the sake of discussion.  I have other apps like Sonar and Nero Wave Editor that I use to create 'product,' and when I'm using them, I probably want them at 50-60 while I'm working, and occasionally at 100 to audition the final results.  And then I have background music which is often on when I'm doing other work, which I tend to like at slightly higher level than system sounds -- maybe, 40?  In all those examples, I still want my 'other' sounds to stay at a moderate level:  there's nothing worse than auditioning a final mix, interrupted by a thundering report of a new email!  So, in my case, 100 is more of an exception than a typical level; having 100 be the starting point when apps open is a bad thing, because 100 = pretty damn loud.  I don't mind occasionally adjusting an app up or down to match a situation, but I don't want to open every other app and find that it's screaming at me.

In my case, mgutt's suggestion of saving off low-volume versions of the system sounds would fix some of the problems, but not all of them.

Regards,
-BW

**Comment by riverar** [comment] 2019-08-02 02:19
Hey folks, want to provide a quick update -- we agree. And we built this feature. We're just jumping through a bunch of hoops to get our EarTrumpet add-on framework ready for use. Apologies for taking so dang long but we're close. I keep you all in the loop.

**Comment by martonx** [comment] 2020-03-02 13:34
Hi, do you have any news? I use Eartrumpet, because of I have a lot of sound related apps are running in the same time.
It is very disappointing to set all of the sound levels after every PC restart.

**Comment by swilliams-dev** [comment] 2020-06-04 17:22
@riverar I'd like to see the settings saved off to a config file that it loads on startup. My use case is that I swap between various audio routing configurations using a combination of "app volume and device preferences", voicemeeter, and nircmd's setdefaultsounddevice to handle various audio profiles (recording, broadcasting, streaming to VRChat, streaming to Discord, desktop mode, vr mode, etc). I do this by taskkilling and replacing configs... very hacky but it works for everything but "app volume and device preferences", which EarTrumpet could solve.

Digging into it, but I may have found an alternative mid-post! lol:
https://blog.nirsoft.net/2020/05/29/set-default-audio-device-of-specific-application-from-command-line-on-windows-10/

**Comment by riverar** [comment] 2020-06-04 18:02
Understood. We rely on Windows to remember audio levels, but despite past assurances by Microsoft that this functionality exists, it doesn't seem to work at all.

Please file a bug in Feedback Hub under [Devices and Drivers] - [Audio and sound]. You can cut and paste from this template (but verify the steps apply to you):

- Summary: Windows does not remember audio levels for application ____
- Explain in more detail: When I start my application, its audio level is reset to 100%, requiring me to change it again.

  Repro steps:
    1. Start application ____
    2. Set audio level to 25%
    3. Close application and restart machine
    4. Start application ____
    5. Observe audio level has reset to 100%

  See also: EarTrumpet/issues/98

Then paste a link here and I'll forward it directly to the audio team.

In the meantime, we have an EarTrumpet add-on built for this and will ship it soon.

**Comment by Ownsin** [comment] 2020-09-05 01:16
Any updates on this? It has been 3 months and no updates on shipping this feature out...

**Comment by mgutt** [comment] 2020-09-21 21:08
> Finally I solved it by reducing the volume of all Windows Notification WAV-files.

Only as feedback. I'm still using this workaround (since one year) and it works perfectly.

**Closed** 2021-02-03 05:44 UTC
Labels: type: feature-request
