### ISSUE TITLE
Quick select for Spacial Sounds

### ISSUE THREAD

**Issue by kokomugi** [File-New-Project/EarTrumpet#488] opened 2020-04-13 22:17 UTC
I would like to use EarTrumplet as a replacement for the volume icon -- however, I do use Spacial Sound in the context menu for quick select of turning Dolby Atmos/etc on and off -- is there any plans to add that into the EarTrumpet menu for quick selection?

**Comment by riverar** [comment] 2020-05-07 08:46
Closing, dupe of #212 but thanks. I need it too!

**Closed by riverar** 2020-05-07 08:46 UTC
