### ISSUE TITLE
The list of applications disappears when the Realtek settings are changed

### ISSUE THREAD

**Issue by D1m0n228** [File-New-Project/EarTrumpet#902] opened 2021-08-22 17:52 UTC
## Description
The list of applications disappears when the Realtek settings are changed

## Steps to reproduce
1. Go to 'Realtek Audio Console'
2. Click on 'Disable all sound effects'
3. Click on 'EarTrumpet

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746

## 
gif animation with the described problem:

![L2C07QTxbE](https://user-images.githubusercontent.com/475132/130367637-97fa0340-0eb2-4500-a963-464c009a94c3.gif)

**Comment by D1m0n228** [comment] 2021-08-22 17:54
http://g.recordit.co/L2C07QTxbE.gif

**Comment by riverar** [comment] 2021-08-22 19:29
Fixed your GIF 👍

**Comment by riverar** [comment] 2021-10-08 22:17
@D1m0n228 Can you restart EarTrumpet, reproduce the issue, then collect diagnostics (Settings > General > About) and attach the resulting file? This file will contain a list of running apps and your username, just a warning.

**Comment by Piwielle** [comment] 2022-01-23 15:54
Hey. Just to add to this, since I think it's relevant, I have the exact same issue, with the same symptoms, when switching between speakers/headphones with my sound card software (Sound Blaster).

I've followed your instructions and did a log.
[tmp4DF4.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/7920789/tmp4DF4.tmp.txt)

I'm running 
- EarTrumpet v 2.1.9.0
- Windows 11, build 22000.438



Is this something that should be fixed by the makers of my sound card software or ?

**Comment by riverar** [comment] 2023-01-26 22:23
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!

**Closed by riverar** 2023-01-26 22:23 UTC
Labels: type: third-party-bug
