### ISSUE TITLE
Notification area icon gets dark, blurry

### ISSUE THREAD

**Issue by pushkine** [File-New-Project/EarTrumpet#183] opened 2018-01-19 04:36 UTC
https://i.imgur.com/ot6WogW.png   
1440p monitor, 125% scaling

**Comment by ChristoferMinestar** [comment] 2018-01-19 15:22
Same problem with 4k 600dpi 250% scaling, restart fixes this.

**Comment by theel0ja** [comment] 2018-01-27 12:09
Same with 4K 150% scaling

![image](https://user-images.githubusercontent.com/5832930/35471811-96485ea6-036b-11e8-9aee-894a8fce080a.png)

**Comment by riverar** [comment] 2018-03-07 15:50
This is a Windows bug; what version of Windows 10 are you on?

**Comment by alexweininger** [comment] 2018-04-05 05:53
having same issue;

150% scaling
2560x1440

Windows 10
Version 1709
Build 16299.334

**Comment by riverar** [comment] 2018-04-08 19:35
I believe the fix for this is in the upcoming Windows update. Let's monitor this one. (You can download third party 1803 ISOs and upgrade today or wait for Windows Update push.)

**Comment by OneCrazyRussian** [comment] 2018-06-09 11:16
Still happens on 1803 when DPI is changed without logging out (RDP, changing resolutions with option to let Windows fix blurry apps turned on)

**Comment by GoldenTao** [comment] 2018-10-14 02:51
Unfortunately still an issue in 1809. Was only able to it on turning scaling down from 175% to 100% before signing out.

**Comment by NiklasSch** [comment] 2018-12-29 21:04
> Still happens on 1803 when DPI is changed without logging out (RDP from different DPI clients or to differrent DPI hosts, changing resolutions with option to let Windows fix blurry apps turned on)

I can confirm, it still happens on 1803.

Funny, the Windows Defender Icon is also effected from the problem. Only a complete Windows restart fix the Windows Defender Icon on my computer.

OK: ![windowsdefender_good](https://user-images.githubusercontent.com/17223557/50542115-01481c80-0bb5-11e9-8854-66ba14f8243e.PNG)

Not OK: ![windowsdefender_blurry](https://user-images.githubusercontent.com/17223557/50542107-e4134e00-0bb4-11e9-8647-c283100b6b93.PNG)

**Comment by niklas389** [comment] 2019-05-30 11:35
Are there any updates on this? I noticed this blurred / not sharp Icon today with the newest version of EarTrumpet. None of the other icons (Windows or 3rd Party app) has this issue.
I'm on Win 10 Build18908 and have a 4K DIsplay with 125% scaling.

**Comment by davuxcom** [comment] 2019-05-30 23:51
Please 
- restart EarTrumpet to clear the log
- Go into Settings / General / About / Collect troubleshooting data and paste the log here
- Take a screenshot with the system audio icon for comparison and paste that here
Thanks

**Comment by niklas389** [comment] 2019-06-04 10:39
![eartrumpet](https://user-images.githubusercontent.com/15279349/58872903-57217300-86c5-11e9-8f3b-dc3b70e6ac76.png)
[tmpFAB5.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/3251863/tmpFAB5.tmp.txt)

Left: EarTrumpet | Right: System
It's really not much - but you can see it and it's not looking good... And since the system icons are being used, there should be a way to make it look like the system one - or not?

**Comment by davuxcom** [comment] 2019-06-04 11:09
Are you at 225% DPI?

(PC Settings / Display / Scale and layout)

**Comment by niklas389** [comment] 2019-06-04 11:10
Oh crap, yeah it's 225% scaling!
Sorry

**Comment by riverar** [comment] 2019-11-26 00:43
@niklas389 Following up, are you still seeing this issue?

**Comment by niklas389** [comment] 2019-12-14 16:36
@riverar 
Nope - it looks as good as the system icon now! Thanks (:

**Comment by riverar** [comment] 2020-02-05 22:51
If anyone is still hitting this issue, please open a new bug.

**Closed** 2020-02-05 22:50 UTC
Labels: type: bug, type: windows-bug
