### ISSUE TITLE
UI Regularly Get's Cutoff

### ISSUE THREAD

**Issue by TooSpooky** [File-New-Project/EarTrumpet#1229] opened 2022-09-20 21:11 UTC
### Summary

Hello,

When using eartrumpet the UI regularly gets cutoff and only fixes itself on restart it seems. It is fine for a bit upon restart and usually has this issue over time.

I am using it in conjunction with Taskbarx so apologies if it is an issue with taskbarx and not eartrumpet. 

<img width="177" alt="YCqo6hsw9p" src="https://user-images.githubusercontent.com/21211292/191364977-e0308053-ea19-409e-a525-1c8a50bb9893.png">

Thanks for your time and take care!

### Steps to reproduce

Launch eartrumpet and wait some time. 

In conjunction with taskbarx usage. 

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.2006

**Comment by riverar** [comment] 2022-09-20 23:49
Do you mind trying a dev build to verify this is fixed correctly? https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

Dupe of #1206

**Comment by TooSpooky** [comment] 2022-09-21 20:39
Sure, I'll give that a download to test it. Thanks!

**Comment by TooSpooky** [comment] 2022-09-22 03:34
At least in quick testing that seems to have completely solved my issue, thanks!

**Comment by riverar** [comment] 2022-09-22 03:47
@TooSpooky Woot! Will get this out to the mainstream shortly.

**Comment by TooSpooky** [comment] 2022-09-22 08:10
Hahah! Sweet, has worked for me all night. Made my volume control infinitely more usable. Thanks again!

**Comment by TooSpooky** [comment] 2022-09-22 09:42
Hahah, spoke too soon. Jinxed it. Had it occur again after being asleep for a decent bit. But still a large improvement from before

**Comment by TooSpooky** [comment] 2022-09-23 00:32
Sure thing. Yeah it stays like that until I restart the app. 

I have a similar issue with taskbarx messing up after a decent sleep but they don’t happen at the same time so not sure they’re connected.

**Comment by TooSpooky** [comment] 2022-09-26 19:27
[tmpF847.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/9649102/tmpF847.tmp.txt)

Here you go. Took a good 4 days of use for it to occur again haha. So it's a lot better than before.

**Comment by riverar** [comment] 2023-01-26 22:07
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1304, thanks!

**Closed by riverar** 2023-01-26 22:07 UTC
