### ISSUE TITLE
Not working with Forza Horizon 3

### ISSUE THREAD

**Issue by wicksy101** [File-New-Project/EarTrumpet#83] opened 2016-09-26 19:46 UTC
Hiya all,

This is not currently working with forza horizon 3. Its a windows app so was hoping this would work but im guessing you need to add them individually. Hope you guys can help out as MS has let us down on this one as the game is unplayable!

**Comment by wicksy101** [comment] 2016-09-26 19:49
Just seen this bug has already been said. Sorry for the spam.

**Comment by benkl** [comment] 2016-09-26 22:19
Second that

**Comment by riverar** [comment] 2016-09-26 22:23
Dupe of #79, my bad for closing it before availability in the Store. We submitted a new version last night, so should be available very soon.

![image](https://cloud.githubusercontent.com/assets/475132/18853963/f9c1edfc-83fc-11e6-8a5b-bf376ec40f0c.png)

We've seen an average of about a day for turn around time.

**Comment by riverar** [comment] 2016-09-27 04:35
Update is now available! Go get it!

**Comment by Hollowman189** [comment] 2016-09-27 04:40
So it works with Forza Horizon 3 now?

**Comment by riverar** [comment] 2016-09-27 04:52
Yep!
![image](https://cloud.githubusercontent.com/assets/475132/18860585/8e82effa-8433-11e6-957a-fb96c216ed8a.png)

**Comment by exts** [comment] 2016-09-27 06:05
WOOHOO, just put it on 2/100 lol - volume is extremely loud with this game

**Comment by ImTheSloth** [comment] 2016-09-27 09:54
i love you guys so much

**Comment by riverar** [comment] 2016-09-27 16:04
Update released.

**Closed by riverar** 2016-09-27 16:04 UTC
Labels: duplicate

**Comment by benkl** [comment] 2016-09-27 17:06
This is some awesome support for free software. Kudos, cake, money, seagulls.
