### ISSUE TITLE
EarTrumpet fails to start when no internet connection is present

### ISSUE THREAD

**Issue by mariobrostech** [File-New-Project/EarTrumpet#1063] opened 2022-02-13 20:14 UTC
### Summary

When setting EarTrumpet to automatically open on startup, it fails to launch unless an internet connection had been established before the program launches. As someone who prefers to manually connect to my Wi-Fi network for security reasons, this presents a major inconvenience to me. Additionally, my laptop, which is set to automatically connect to my home Wi-Fi, also occasionally fails to start EarTrumpet since the app will launch before I'm authenticated on the network.

Is there any reason why EarTrumpet would require an internet connection, even when analytics reporting is disabled in the program's settings?

The error displayed reads "CLiP device license not found." I've attached a screenshot in the Additional Information section, which you can see below.

### Steps to reproduce

1. Set EaraTrumpet to automatically launch on startup.
2. Disable automatic re-connection to Wi-Fi or Ethernet on startup.
3. Observe EarTrumpet fail to start with an error message on the next login.

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19044.1526

### Additional information

![image](https://user-images.githubusercontent.com/17557442/153772807-e1517ff9-3b5b-4e84-a87d-b8483ed2325a.png)

**Comment by riverar** [comment] 2022-02-14 00:25
Hm, I can't reproduce this. Are you on Windows 10 Pro or something different? Was this app grabbed from the Store directly or installed via AppInstaller or other means? How long was this machine without Internet access?

**Comment by mariobrostech** [comment] 2022-02-14 00:50
Hi there, thanks for looking into this! I'm currently running Windows 10 Pro, and the app was installed directly via the Microsoft Store. The PC in question is always connected to the internet, with the exception of it being disconnected on boot due to auto-joining Wi-Fi networks being disabled.

**Comment by riverar** [comment] 2022-02-14 05:51
@mariobrostech Interesting hm. Is Wi-Fi your only Internet access method? (No Ethernet, right?) 

For some reason, the Microsoft Store thinks it's necessary to _license_ a free app and that license (for whatever reason) is expiring, not getting installed, etc. hence the error. It's out of our control but I do want to narrow this down to file a bug on Windows.

**Comment by mariobrostech** [comment] 2022-02-14 07:27
@riverar Thanks again for looking into this for me. I will occasionally use Ethernet, but it’s usually something that I switch to after the PC has already been booted for a while, making it irrelevant for a boot-time issue like this. It doesn’t seem to happen on every boot, but that’s again because my Wi-Fi sometimes connects before EarTrumpet loads, and sometimes it takes a little while longer to authenticate on the network. As I continue using my PC, I’ll keep a closer eye on if there’s a pattern to the way the error message is being generated.

**Comment by EAZY5D** [comment] 2022-09-08 07:48
Try windows 11 22h2 Beta channel that should help with reproducing the bug I tried that on 2 laptops and I was unable to start ear trumpet without internet

**Comment by riverar** [comment] 2023-01-26 22:38
Hi there. I'm cleaning up the issues list. There's no work to be completed here right now so am closing this issue for now. (We'll keep evaluating our offering in the Microsoft Store. As a workaround, you can use Chocolatey or other channels for non-Microsoft licensed packages.) Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 22:38 UTC
Labels: status: can't reproduce, type: windows-bug

**Comment by swasher** [comment] 2025-08-30 06:21
2025 year - same error. If no ethernet connection during startup - I got this error.
