### ISSUE TITLE
EarTrumpet pop-up says I have no playback devices when I do

### ISSUE THREAD

**Issue by Ceiyne** [File-New-Project/EarTrumpet#249] opened 2018-06-26 14:45 UTC
Up until recently EarTrumpet has been working flawlessly for me.  Recently it started to sometimes show "It doesn't look like you have any playback devices" when I open the pop-up by clicking on the EarTrumpet icon.  This isn't true; I actually have several playback devices.  EarTrumpet can even see them, because they are displayed when I open the EarTrumpet Volume Mixer window.  

If I exit EarTrumpet and start it back up again, then the pop-up starts working again for a while.  I'm not positive, but I think the problem may occur after a sleep/wake cycle on my PC.

**Comment by ICDeadPpl** [comment] 2018-06-28 11:00
I can confirm this, it happens after waking up the computer from sleep.
Exiting and restarting EarTrumpet makes the pop-up work again.

**Comment by riverar** [comment] 2018-07-03 23:33
Dupe of #233 but thanks for the scenario (sleep). We'll try to reproduce this again.

**Closed by riverar** 2018-07-03 23:33 UTC

**Comment by iamjaydear** [comment] 2023-06-19 00:33
Using v2.2.2.0 and have this problem today on my 2022 ASUS lappie June 2023. It was working OK up to now afaict. Are you still working on this app?
