### ISSUE TITLE
Skip, pause and back skip don't work after launching EarTrumpet.

### ISSUE THREAD

**Issue by ChristoferMinestar** [File-New-Project/EarTrumpet#179] opened 2018-01-08 18:56 UTC
Skip, pause and back skip don't work after launching EarTrumpet on a Dell XPS 15 9550. They don't work again until after a cold boot.

**Comment by riverar** [comment] 2018-03-07 15:58
Can you confirm those controls work if you disable EarTrumpet startup? We don't do anything that would cause this, so am a little suspicious.

**Comment by riverar** [comment] 2018-06-13 05:35
Closing this bug because we can't reproduce this. But give EarTrumpet 2.0 a try, it may have fixed your issue. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Closed by riverar** 2018-06-13 05:35 UTC
Labels: can't repro
