### ISSUE TITLE
Error: Windows cannot find "[...] EarTrumpet.exe'. Make sure you typed the name correctly, and then try again

### ISSUE THREAD

**Issue by rurot10** [File-New-Project/EarTrumpet#274] opened 2018-07-31 01:22 UTC
This weekend July 28th my laptop did a windows update.  And it went through the regular restarts and when all was done rebooting and loading the final time Windows 10 displayed the following. 

<img width="387" alt="eartrumpet error" src="https://user-images.githubusercontent.com/41931436/43431780-a3e322ae-943d-11e8-9427-593f25dfde9c.png">

Windows cannot find "C:\Program Files\WindowsApps\40459File-New-Project_2.0.4.0_x86__1sdd7...\EarTrumpet.exe'.
Make sure you typed.....

I uninstalled EarTrumpet cleaned the registry, rebooted and reinstalled the program.  Before starting the program again, I rebooted and attempted to start the program with the same message displayed.  

Please advise?
John

**Comment by riverar** [comment] 2018-07-31 03:07
Hi @rurot10, what build/version of Windows 10 are you using? (Start > Run > winver)

**Comment by brutlern** [comment] 2018-07-31 07:05
Same thing is happening to me, but a slightly different error message. It seems to happen randomly though and only a Windows restart fixes it.

![capture2](https://user-images.githubusercontent.com/39137520/43442978-4c37c710-94a8-11e8-8680-2f268ab7b2f0.JPG)

Windows version is version 1803 (OS build 17134.165).

**Comment by rurot10** [comment] 2018-07-31 12:29
Version 1803 (OS Build 17134.191)

**Comment by riverar** [comment] 2018-08-06 04:01
This might be related to a recently fixed Windows bug. Can you try installing the following patch?
https://support.microsoft.com/en-us/help/4340917/windows-10-update-kb4340917

**Comment by rurot10** [comment] 2018-08-06 17:52
Rafael, the update was already installed on my machine.  I again performed an un-install and an install with reboot but with the same message.  Any other suggestions. 



John Fry
859-621-9998 (txt OK)

**Comment by Runaway254** [comment] 2018-08-08 17:08
I was having the same issue as rurot10, even after re-installing KB4340917. 

I found a workaround by editing the security settings and making myself the owner of the WindowsApps folder as described [here](https://www.maketecheasier.com/access-windowsapps-folder-windows-10/), then launching EarTrumpet.exe manually from the folder:

`C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.5.0_x86__1sdd7yawvg6ne\EarTrumpet`

Trying to launch it through the start menu throws an error saying "The parameter is incorrect."

**Comment by tomzorz** [comment] 2018-10-04 23:45
Got the same issue after updating to RS5. I installed the app on RS4 from the store originally.

"+1" on feedback hub https://aka.ms/AA2qs1y

![image](https://user-images.githubusercontent.com/6363312/46508953-4839a680-c840-11e8-9904-b8dc0ee463bd.png)

**Comment by spikespaz** [comment] 2018-10-07 18:58
This happens to me when I took ownership of my WindowsApps folder. It broke several programs, and I tried to give permission back to TrustedInstaller but it just caused more problems. Based on my research the only way to resolve this is a complete reinstall of Windows.

Microsoft, I own my damn computer. Let me do what I want.

**Comment by mr4ffe** [comment] 2018-12-18 21:15
Still not fixed.

**Comment by wooziwoozi** [comment] 2019-04-01 03:08
I am having this issue now.

**Comment by edumlauer** [comment] 2020-01-01 17:36
I was having the same problem. Removed the app and now I can't reinstall it. The only message I get from Microsoft Store is "Couldn't Install. We'll  try again later.".

**Comment by Irwinori** [comment] 2020-12-23 17:41
did you guys found solve for the problem its been 2 years and no one fix it!

**Comment by Irwinori** [comment] 2020-12-23 17:42
@riverar did you guys found solve for the problem its been 2 years and no one fixes it!

**Comment by riverar** [comment] 2020-12-23 18:09
@Irwinori This is a low occurrence non-reproducible Windows bug, sorry. Are you on an older Windows 10 release by any chance? You'll likely have better success with newer releases of Windows 10.

**Comment by Irwinori** [comment] 2020-12-23 18:11
@riverar am at the last version of windows 10 every app in the store work fine i try to repair it but nothing

pls help i love it and i need it

**Comment by riverar** [comment] 2020-12-23 18:19
@lrwinori I just sent another email to Microsoft again. In the meantime, can you use Chocolatey? `choco install eartrumpet`

**Comment by Irwinori** [comment] 2020-12-23 18:21
@riverar is it save to use because it will be my first time to use it

thank u for ur hard work to making our lives easier

**Comment by riverar** [comment] 2020-12-23 18:26
@Irwinori It's safe, we maintain the package ourselves. For more information, see https://chocolatey.org/packages/eartrumpet.

**Comment by Irwinori** [comment] 2020-12-23 19:21
@riverar I install it and its working in a good way, if u can update things up and fix it that's will be cool

**Comment by Irwinori** [comment] 2021-05-11 10:45
@riverar any update or fix for the problem?

**Comment by Irwinori** [comment] 2021-05-11 11:12
i think the problem with the registry

**Comment by riverar** [comment] 2023-01-26 21:01
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 21:01 UTC
Labels: type: windows-bug

**Comment by MiRorshik** [comment] 2023-07-26 00:23
Congratulations guys, it's been 5 fucking years and the problem hasn't been fixed. I have the same thing on windows 11, it is now there.

**Comment by MiRorshik** [comment] 2023-07-26 00:26
Why close the topic if the problem is not solved?

**Comment by wooziwoozi** [comment] 2023-07-26 01:33
> Congratulations guys, it's been 5 fucking years and the problem hasn't been fixed. 

This is a free application made in their free time. Please show some respect and drop the entitlement. You are not owed anything.

**Comment by riverar** [comment] 2023-07-26 05:16
Sorry for the headaches on this one. I closed it because there's nothing actionable on our side.

@drustheaxe Hey Howard, I keep getting beat up on this bug, pretty sure something is broken in appmodel or centennial and now got our first Windows 11 report. Any debugging tips here? Tracing?

**Comment by DrusTheAxe** [comment] 2023-07-26 23:21
> This happens to me when I took ownership of my WindowsApps folder. It broke several programs

Yeah. That directory and children have various ACLs crafted on them (and often weirder and more complicated than you find elsewhere in Windows). Messing with that's usually destructive (depends on the tools and exactly what was done). We've hardened the ACLs over the years to make that sort of well-intentioned-malice harder to accomplish but devs are wily and creative...

I'm not sure if there's any easy 'fix' for that. It's akin to jogging thru the C:\Windows directory tree with a blowtorch, watching Windows wilt and cry in various ways then asking for a way to 'fix' it... I'm not overly optimistic but perhaps there's a trick I'm unaware of. Will see what I can dig up.

**Comment by riverar** [comment] 2023-07-26 23:26
The scenario where a user tinkers in WindowsApps is invalid, wouldn't worry about that one. But we've had a significant number of folks just fail out of the blue and at one point I thought it was a Centennial bug...

@MiRorshik Did you mess with the WindowsApp folder at all?

**Comment by DrusTheAxe** [comment] 2023-07-27 02:43
> folks just fail out of the blue and at one point I thought it was a Centennial bug...

Hard to say. Variety of reasons things could fail. One simple check you can do is look at the Microsoft-Windows-AppxDeploymentServer/Operational eventlog in the Event Viewer (Win-X, EventViewer or eventvwr.exe)

![image](https://github.com/File-New-Project/EarTrumpet/assets/72222/3e4fecd9-0f21-4af1-807d-7f2401cb40cf)

Deployment operations typically log "starting deployment operation" event, several events about actions during that (including errors if they occur) and an "completed deployment operation" event. When errors occur one or more of those events in the middle typically have a smoking gun pointing to the root cause (or at least a steaming slingshot hinting at it).

If everything was installed fine but something was busted and only noticed when activating the app it's a bit harder as activation doesn't persist events to the eventlog (the perf impact is undesirable given how often processes launch...). Activation does report ETW events, but they're more complicated to understand or root cause. If you use FeedbackHub with the right category and enable Tracing, repro the problem and end tracing it'll collect activation ETW events (and related) and reported to Microsoft.

**Comment by kavemang** [comment] 2024-02-02 17:47
my app store is completely screwed up no idea why, now ear trumpet wont run because of that

anyone know of a way to run it totally independent of microsofts bullshit? or an alternative software that does the same thing?

**Comment by ibay770** [comment] 2025-05-15 06:54
I have had success just copying the eartrumpet folder elsewhere and running it. 
Also try this instead of the store app, All the apps are simply in a fancy zip format, msix or appxbundle can be extracted with 7zip, they should work most of the time by default.
https://github.com/mjishnu/alt-app-installer/releases
