### ISSUE TITLE
EarTrumpet Blocking Display Mode Change NVIDIA

### ISSUE THREAD

**Issue by Reggie119** [File-New-Project/EarTrumpet#1464] opened 2023-10-05 18:06 UTC
### Summary

When the laptop is set to Automatic Display Mode Switch(Advanced Optimus or Hybrid Mode in my case through Lenovo Vantage)
while EarTrumpet is running auto switching is blocked. 

My laptop is the Lenovo LOQ i7 13700h RTX 4060

<img width="734" alt="Screenshot 2023-10-06 014801" src="https://github.com/File-New-Project/EarTrumpet/assets/60596258/b6e3b747-b0cd-425e-bb16-353c7a641fea">

No problems when EarTrumpet is not running.

### Steps to reproduce

Select hybrid mode on lenovo vantage software.
Have eartrumpet running

Attempt to start a 3D application or game. In my case I used 3DMark.

NVIDIA will attempt to switch GPUs several times but fail due to EarTrumpet.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22621.2361

### Additional information

NVIDIA Display Driver Version 537.42

Troubleshooting Data:

[tmp364D.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/12821685/tmp364D.tmp.txt)

**Comment by riverar** [comment] 2023-10-05 18:46
That's interesting because we force the app into software rendering

https://github.com/File-New-Project/EarTrumpet/blob/bde6b6b6d698bbe85a55733f4e4de28129abceb9/EarTrumpet/App.xaml.cs#L45-L48

If you open that terrible GPU activity app (NVIDIA control panel > Desktop > Display GPU Activity In Notification Area), does EarTrumpet show up at all?

**Comment by Reggie119** [comment] 2023-10-06 06:27
Nope. EarTrumpet does not show up.

<img width="516" alt="image" src="https://github.com/File-New-Project/EarTrumpet/assets/60596258/bb1020d6-b8b4-4cb4-bb76-8269b3c5d620">

**Comment by AudreyAP** [comment] 2023-11-17 21:16
I mistakenly commented on #771 as well, but I am having this issue on current eartrumpet.

**Comment by riverar** [comment] 2023-11-24 18:20
I can't reproduce this locally and NVIDIA doesn't seem to have any documentation on what this feature does. I'll ask around but it's going to be tough to move forward on this issue without more info.

**Comment by AudreyAP** [comment] 2023-11-24 19:10
Not even Microsoft knows how to do it properly, apparently - the "phone link" app has the same issue.

**Comment by mikooomich** [comment] 2023-11-29 04:12
This could have something to do with HDMI audio and/or putting the laptop to sleep. IIRC disabling all the HDMI audio outputs seems to resolve this on my end for the most part. My display outputs are routed through the dGPU.

**Comment by blackk100** [comment] 2023-12-23 05:44
I am also facing this issue on the latest EarTrumpet release (2.3.00); Windows 11 22631.2861; coincidentally, also on a Lenovo (Legion Slim 5 16APH8, RTX 4060).

I can manually force the display output to change using the NVIDIA control panel/dynamic display mode tray icon, but Advanced Optimus fails. Disabling HDMI audio outputs doesn't resolve it in my case.

**Comment by riverar** [comment] 2023-12-23 06:23
Thanks for the data @blackk100, I'm hoping for feedback from NVIDIA. The US is mostly on holiday break so I don't expect a response for a few additional weeks.

**Comment by blackk100** [comment] 2024-02-20 22:36
I no longer have this issue on v551.52 of the GeForce driver.

**Comment by riverar** [comment] 2024-03-04 05:31
Thanks for the heads up @blackk100. I reached out to NVIDIA again but with their laser focus on AI at the moment, doubt we'll ever hear back. Closing this for now, but if anyone still has this issue with 551.52 or higher, please let us know.

**Closed by riverar** 2024-03-04 05:31 UTC
Labels: status: can't reproduce, status: blocked

**Comment by riverar** [comment] 2025-02-18 21:01
Closing the loop, NVIDIA reports this is fixed in 555.xx or higher.
