### ISSUE TITLE
Windows legacy window cant be opened

### ISSUE THREAD

**Issue by pixpeel** [File-New-Project/EarTrumpet#429] opened 2019-10-11 06:19 UTC
whenever I click the windows legacy button and try to move to the popup menu it closes before I can make a selection(this doesn't happen when using the taskbar on the left of the screen).

![image](https://user-images.githubusercontent.com/43709906/66628593-82a8f280-ebbc-11e9-90dd-859d0bc477dd.png)

**Comment by riverar** [comment] 2019-10-11 06:19
@pixpeel Is this happening on your non-primary display?

**Comment by pixpeel** [comment] 2019-10-11 06:26
> @pixpeel Is this happening on your non-primary display?

Yes however I get the same thing on my primary
(also I can occasionally move my mouse quickly in a certain way to get it to work)

**Comment by riverar** [comment] 2019-10-11 06:41
@pixpeel When this happens on your primary display, is it after you've moved the taskbar? Does it persist if you restart EarTrumpet after moving the taskbar?

**Comment by pixpeel** [comment] 2019-10-11 06:57
> @pixpeel When this happens on your primary display, is it after you've moved the taskbar? Does it persist if you restart EarTrumpet after moving the taskbar?

yes it is consistent even after restarting my computer or eartrumpet

**Comment by pixpeel** [comment] 2019-10-11 07:31
> @pixpeel When this happens on your primary display, is it after you've moved the taskbar? Does it persist if you restart EarTrumpet after moving the taskbar?

![002](https://user-images.githubusercontent.com/43709906/66632931-de787900-ebc6-11e9-8f30-54bda36c8a62.gif)

**Comment by riverar** [comment] 2019-10-11 17:39
Got it thanks. Dupe of #399.

**Closed by riverar** 2019-10-11 17:39 UTC

**Comment by riverar** [comment] 2019-10-11 17:40
Just heads up, this is fixed in our dev branch https://github.com/File-New-Project/EarTrumpet/commit/46c7bc983b5d31e3f6a0c0779da021375b043e3c will be in the next update. Thanks!
