### ISSUE TITLE
Moving the volume mixer is weird....

### ISSUE THREAD

**Issue by thebluedev** [File-New-Project/EarTrumpet#853] opened 2021-06-13 16:42 UTC
## Description
Moving around the volume mixer windows is laggy?

## Steps to reproduce
1. Go to the system tray and right click
2. Click on volume mixer
3. try to move around the opened window

It kinda seems like it's lagging

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: x64 build 19043

**Comment by riverar** [comment] 2021-06-13 18:28
Closing as duplicate of pinned issue #349 :)

**Closed by riverar** 2021-06-13 18:28 UTC
Labels: type: bug
