### ISSUE TITLE
EarTrumpet listing random Nvidia process

### ISSUE THREAD

**Issue by D4n2021** [File-New-Project/EarTrumpet#1376] opened 2023-05-22 21:17 UTC
### Summary

"nvcontainer" entry shouldn't appear in volumemixer. Even after restarting EarTrumpet, it is still listed.

### Steps to reproduce

Have Nvidia driver 531.79 installed, have the entire EarTrumpet volumemixer window open, have "desktop-recording" enabled in GeForce Alt+Z overlay settings and use LAlt+F10 to save screendata. Then at some point "nvcontainer" should appear in there.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19045.2965

### Additional information

![grafik](https://github.com/File-New-Project/EarTrumpet/assets/20766261/a23e31c6-f4c4-4a55-a3e0-2094d57ec4e4)

**Comment by riverar** [comment] 2023-05-26 01:43
This means the process has an active audio session. It probably played a tiny blip sound when you took a screenshot. I'll see if I can reproduce this but thus far not convinced there's a problem.

**Comment by DeveloperBlue** [comment] 2023-05-29 09:58
I've also had this "issue" for a few months. It's a byproduct of having Nvidia GeForce Experience's "Instant Replay" feature on, where it's always recording your gameplay for quick retroactive captures.

I wouldn't want to lose this feature, and since it doesn't look like there's any alternatives Nvidia might pursue any time soon, might I suggest the solution lies with #713 - Hide unnecessary app volume [Feature] or #678 - Add display filtering (exclusions) of audio devices shown in list?

**Comment by riverar** [comment] 2023-06-21 05:03
Agree, will close this issue and keep tracking via https://github.com/File-New-Project/EarTrumpet/issues/1382 where I'm adding filtering UI. Thanks!

**Closed by riverar** 2023-06-21 05:03 UTC
