### ISSUE TITLE
Flyout does not dismiss when returning focus to a fullscreen game

### ISSUE THREAD

**Issue by Motifier** [File-New-Project/EarTrumpet#311] opened 2018-12-02 22:17 UTC
When a full screen application is open, typically it has been games for me like PUBG / SCUM / League of Legends. The application does not automatically close when you click away.

**Comment by riverar** [comment] 2018-12-04 04:47
@Motifier Can you provide more details, screenshot, video, anything? I tried a few games, including PUBG, and can't reproduce.

**Comment by Motifier** [comment] 2018-12-04 05:06
Hi River, here is video demonstrating what I mean. It appears that if you scroll to change the sound level and then click away (but never click on the application) it does not go away. If you click and drag anywhere on earTrumpet then it does go away.

I've uploaded a video here for clarity - https://youtu.be/nQGz4x0GQgA

**Comment by riverar** [comment] 2018-12-04 08:53
Interesting. So can you verify these are the steps you're following?

1. Open PUBG
2. Hit Windows Key
3. Click EarTrumpet in notification area
4. Use scroll-wheel to adjust app volume
5. Click PUBG to dismiss EarTrumpet
[EarTrumpet does not dismiss]

**Comment by riverar** [comment] 2018-12-04 09:13
Can reproduce, thanks for the video!

**Comment by Motifier** [comment] 2018-12-04 09:53
Hi Riverar,

Yes, thats exactly what I'm doing. No problem regarding the video, I do a lot of the same for work.

Love the application, hopefully its an easier fix.

Cheers,
Tom

**Comment by Motifier** [comment] 2018-12-12 09:49
Hi @riverar , Any idea when this would be included in the next windows store build?

Cheers,
Tom

**Comment by riverar** [comment] 2018-12-12 09:52
Hey @Motifier, due to Microsoft Store submission deadlines, will unlikely be this year. But it's fixed in dev if you're interested in compiling your own copy. Will work on nailing this down and let you know.

**Comment by Motifier** [comment] 2019-03-05 20:16
Hi @riverar ,

I was just checking back in to see if there had been a final commit for the Microsoft Store? I was going to compile a dev copy but notice you striked "its fixed"

Cheers,
Tom

**Comment by Motifier** [comment] 2019-03-28 02:14
Hi @riverar ,

Is this still fixed in Dev? is it worth me compiling a version?

Cheers,
Tom

**Comment by riverar** [comment] 2019-04-08 05:40
@Motifier Thanks for your patience; we pushed out what was in dev in 2.1.1.0, give that a whirl. If not, I'll make this higher priority for the next bugfix release. I'll also let you know when a fix lands in dev so you can try it out immediately.

**Comment by davuxcom** [comment] 2019-06-11 16:26
The bug here is actually (seemingly) in the Windows shell giving EarTrumpet foreground rights when activating from the notification icon.  Perhaps there is some bug in our code, bug foreground rights are per-process and the below test seems to match the described behavior.

This is the behavior I observe when I have a fullscreen borderless game running:

1. Open EarTrumpet by typing <kbd>WIN</kbd> to reveal the Taskbar.
2. Click the EarTrumpet icon (not in overflow) in the notification area.
Observe: 
- EarTrumpet flyout opens, but pressing <kbd>RightArrow</kbd> or <kbd>LeftArrow</kbd> doesn't change the master volume.  In fact focus has been sent back to the game window, or hasn't left the taskbar.  Sometimes pressing tab will reveal keyboard focus on the taskbar.

Repeat the above with either:
- Hotkey invoke (assign in Settings): Focus goes to the EarTrumpet flyout and left/right keys change the volume
- Debugger attached: Focues goes to EarTrumpet because the debugger suppresses foreground rights enforcement.

There is no simple solution since the flyout is visible on the screen, but it is not focused.  You also see that when you're in the scenario, clicking the focus will give it focus, and then you can dismiss it by typing <kbd>ESC</kbd> or clicking away.

**Comment by vertigo220** [comment] 2020-06-27 19:22
I get this _all the time_ with Windows' pop-ups, so I would agree that it's a problem (one of many) with Win10, which is, after all, probably the buggiest version of Windows since Me (and I actually don't recall it being this bad).

**Comment by riverar** [comment] 2023-01-26 21:02
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 21:02 UTC
Labels: type: windows-bug
