### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by fgsfds** [File-New-Project/EarTrumpet#515] opened 2020-06-20 06:14 UTC
This happens from time to time and doesn't go away unless I restart ET. 

![image](https://user-images.githubusercontent.com/4870330/85194495-2e2b4a80-b2e7-11ea-9321-a3c0c60ec37d.png)

**Comment by vertigo220** [comment] 2020-06-27 18:49
If you provide more info, such as OS version and build, how often this happens, what your CPU is, etc, it might help the devs troubleshoot.

**Comment by riverar** [comment] 2020-06-27 20:10
Indeed, next time this happens please:
1. Open Task Manager
2. Right-click `EarTrumpet (32 bit)` and click Create Dump
3. Compress the dump (e.g. via 7zip) and email it to `team@eartrumpet.app`

Thanks!

**Comment by MPeti1** [comment] 2020-11-16 07:08
I experience this from time to time, too. Would it help if I email a dump too when this occurs?

**Comment by riverar** [comment] 2020-11-16 09:10
@MPeti1 Absolutely. When you see it happening, grab a dump. Thanks!

**Comment by MPeti1** [comment] 2020-11-17 23:59
Just a quick note: it seems not every connection/disconnection does this.
For example a few seconds ago disconnection didn't seem to make EarTrumpet have measurable CPU usage, and connection only made it to use 2-3%
![image](https://user-images.githubusercontent.com/9215491/99464744-1b21b280-2939-11eb-8252-b950d02154db.png)

**Comment by riverar** [comment] 2021-02-24 08:29
Don't think we've received any dumps yet.

Closing for now as we can't reproduce this. Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. (And get those dumps to us!) Thanks!

**Closed by riverar** 2021-02-24 08:29 UTC
Labels: status: can't reproduce

**Comment by MPeti1** [comment] 2021-02-24 22:57
> Don't think we've received any dumps yet.

I haven't seen doing it since, so yeah. It might have been a temporary bug

**Comment by riverar** [comment] 2021-02-24 23:15
@MPeti1 Glad it's not happening anymore though, thanks for following up!

**Comment by fgsfds** [comment] 2021-07-12 08:16
It happened again. Was finally able to grab a dump.

![image](https://user-images.githubusercontent.com/4870330/125253686-1d46e000-e313-11eb-90a1-e877f9db6891.png)

**Comment by Dave3848** [comment] 2025-07-30 10:38
2025 and it's still happening. Neat.
