### ISSUE TITLE
The panel is only partially displayed

### ISSUE THREAD

**Issue by B-W3ng** [File-New-Project/EarTrumpet#1148] opened 2022-05-09 08:11 UTC
### Summary

音量调节面板中最下面的几个应用的音量调整会被任务栏遮盖，并且完全无法显示或者调出，就无法调节音量了。只有重启应用才能解决。

The lowermost apps in the volume adjustment panel will be covered by the taskbar, and cannot be displayed or recalled at all, so the volume cannot be adjusted. Only restarting the eartrumpet can solve it.

### Steps to reproduce

当我右键打开原生windows的音量调节，并更改空间音效时，此bug必定被触发。

This bug will be 100% triggered when I right-click native windows volume icon and change the spatial sound effect(like DTS or Dolby).

### EarTrumpet version

2.1.10.0

### Windows version

10.0.19044.1682

### Additional information

![屏幕截图 2022-05-09 160206](https://user-images.githubusercontent.com/77229078/167367838-6810732d-acb7-4f82-8e49-592ab5e52f43.png)
![屏幕截图 2022-05-09 160940](https://user-images.githubusercontent.com/77229078/167367848-db8740b6-5c0c-4782-a306-f0b98cff2c73.png)

**Comment by riverar** [comment] 2022-05-22 18:04
Closing as duplicate of #977 #1049 and others. Thanks!

**Closed by riverar** 2022-05-22 18:04 UTC
