### ISSUE TITLE
volume mixer

### ISSUE THREAD

**Issue by OmegaDL2** [File-New-Project/EarTrumpet#583] opened 2020-11-26 18:41 UTC
when you move the volume mixer from ear trumpet it moves very slowly, about half the velocity from your mouse

**Comment by riverar** [comment] 2020-11-26 18:44
@OmegaDL2 Thanks, this is a dupe of #349. Will track over there.

**Closed** 2020-11-26 18:44 UTC

**Comment by OmegaDL2** [comment] 2020-11-26 18:48
yeah, i saw it later
