### ISSUE TITLE
Feature request: add support for managing recording devices as well

### ISSUE THREAD

**Issue by cfischer69** [File-New-Project/EarTrumpet#121] opened 2017-04-19 15:41 UTC
The playback device functionality is great.  I'd love to have the same capabilities for recording devices as well.  I have several and often need to switch between them and/or blend them.

**Comment by mortenlerudjordet** [comment] 2018-06-29 16:13
This would be super nice

**Comment by karisinkko** [comment] 2018-11-12 00:13
Yes, this would be logical.

**Comment by NathanRTracy** [comment] 2019-05-04 08:16
I would love to have this feature, as well. That would make this be a complete audio interface manager.

**Comment by ThomasBergholdWieser** [comment] 2019-05-09 14:28
Would to be able to replace Audio Switcher with this.

**Comment by ICDeadPpl** [comment] 2020-02-11 08:56
This would be great!

**Comment by narspt** [comment] 2020-06-26 05:22
+1

**Comment by vertigo220** [comment] 2020-06-27 19:44
Appears to be duplicate of #99

**Closed** 2021-02-03 05:44 UTC
Labels: type: feature-request
