### ISSUE TITLE
Volume value doesn't change when hovering over tray icon and scrolling

### ISSUE THREAD

**Issue by silverwings15** [File-New-Project/EarTrumpet#1352] opened 2023-04-19 10:09 UTC
### Summary

The volume value in the tooltip that appears when you hover over EarTrumpet's tray icon, doesn't automatically update when you scroll to adjust.

### Steps to reproduce

1. Hover over EarTrumpet's tray icon
2. Wait for tooltip to appear
3. Scroll up or down to adjust the volume.
4. The speaker graphic will change based on the adjustment, but the number in the tooltip doesn't

### EarTrumpet version

2.2.0

### Windows version

10.0.22621.1265

**Comment by riverar** [comment] 2023-04-19 15:29
Duplicate of https://github.com/File-New-Project/EarTrumpet/issues/1298 and already fixed in dev builds. Will get that to the rest of the users soon!

**Closed by riverar** 2023-04-19 15:29 UTC
