### ISSUE TITLE
EarTrumpet sometimes does not correctly open

### ISSUE THREAD

**Issue by prakharb5** [File-New-Project/EarTrumpet#560] opened 2020-09-02 06:15 UTC
EarTrumpet sometimes opens partly covering the taskbar.

![image](https://user-images.githubusercontent.com/51435948/91938479-b4b1ce80-ed11-11ea-8360-7c1d02dfa345.png)

**Comment by riverar** [comment] 2020-09-27 18:21
Thanks, we see this from time to time but cannot reproduce it reliably enough to fix at this time. If you figure out repro steps, let us know!

**Comment by Cyberdroid1** [comment] 2020-09-28 04:45
Maybe just summon the window repetitive types? That's all I can say for it.

**Comment by riverar** [comment] 2023-01-26 22:03
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 22:03 UTC
Labels: status: can't reproduce, type: windows-bug
