### ISSUE TITLE
overkill enhancement: choosable outputDevice for each program

### ISSUE THREAD

**Issue by homelessgamer** [File-New-Project/EarTrumpet#82] opened 2016-09-25 22:38 UTC
you will have very hard times trying to use two output devices at once. your only chance is that your used program has good audio settings which allow to set the output device for this specific program. most dont have this. would be cool if i could set this option in my favourite audio mixer "earTrumpet"

TLDR: let me configure the output device for each program in ear trumpet

**Comment by riverar** [comment] 2016-09-25 23:45
Duplicate of a popular feature request (#61), thanks!

**Comment by GoldenTao** [comment] 2016-10-08 07:54
Any updates to this one will be in #61.

**Closed by GoldenTao** 2016-10-08 07:54 UTC
Labels: duplicate, enhancement
