### ISSUE TITLE
Multiple EarTrumpet instances started

### ISSUE THREAD

**Issue by beppe9000** [File-New-Project/EarTrumpet#457] opened 2020-01-11 14:48 UTC
![image](https://user-images.githubusercontent.com/6625123/72206049-cfd18480-3489-11ea-9aa4-a9048265c62c.png)

**Comment by riverar** [comment] 2020-01-14 04:57
Do you have multiple instances of EarTrumpet.exe running? (See Task Manager.) I suspect this is just a dupe of #404, which we'll fix in the next update.

**Comment by beppe9000** [comment] 2020-01-14 13:27
I actually had multiple processes.

**Comment by riverar** [comment] 2020-01-14 19:21
You saw multiple EarTrumpet.exe processes? Or are you just assuming it was multiple because they were interactive/working tray icons?

https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/App.xaml.cs#L43-L60

**Comment by beppe9000** [comment] 2020-01-14 19:44
I had multiple entries in task manager process tab

**Comment by mswiecic** [comment] 2020-01-17 14:00
I had also multiple EarTrumpet icone in the dock. Two of them had grayed icons. I think it happen when I switch monitor from external to built-in my laptop and back.
In task manager is only one EarTrumpet process.

![Adnotacja 2020-01-17 145526](https://user-images.githubusercontent.com/22434990/72617758-f84df880-3939-11ea-88ed-0042e4b4b943.jpg)
![Adnotacja 2020-01-17 145544](https://user-images.githubusercontent.com/22434990/72617759-f84df880-3939-11ea-8416-8808fbde6520.jpg)
![Adnotacja 2020-01-17 145613](https://user-images.githubusercontent.com/22434990/72617760-f8e68f00-3939-11ea-9504-0ed9afc15f81.jpg)

**Comment by riverar** [comment] 2020-01-19 23:00
Closing as dupe of #404, will push an update today.

**Closed by riverar** 2020-01-19 23:00 UTC
Labels: status: can't reproduce
