### ISSUE TITLE
Win10 20H2 CPU high usage rate and animation slowly

### ISSUE THREAD

**Issue by Xionghaizi001** [File-New-Project/EarTrumpet#819] opened 2021-05-01 14:34 UTC
## Description
1.When system has some big program started or has some bugs, EarTrumpet will use over 40% CPU.
2.The animation is slowly and high resource usage.

## Steps to reproduce
Just click its icon.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.928

## Screenshots
No.

**Comment by maxplayle04** [comment] 2021-05-09 22:48
I'm also experiencing this. 

## Meta
• Ear Trumpet Version: 2.1.8.0
• Win10 19042.928
(same as in the original issue)

**Comment by riverar** [comment] 2021-05-09 23:56
Closing this issue as it's a duplicate of #349. A workaround exists in dev builds; fix is in the next release of Windows 10.

**Closed by riverar** 2021-05-09 23:56 UTC
Labels: type: bug
