### ISSUE TITLE
Changing default output device does not change default communication device

### ISSUE THREAD

**Issue by BlueRaja** [File-New-Project/EarTrumpet#454] opened 2019-12-30 00:46 UTC
REPRO STEPS:
1. Right-click Ear Trumpet in the task bar
2. Click on a different output device
3. Right-click again --> Windows Legacy --> Playback Devices

EXPECTED RESULTS:
The chosen output device is the only one with a green symbol

ACTUAL RESULTS:
The new device has a green checkmark but the old device has a green "phone" symbol, representing that it's still the "default communication device".  This is the "default device" that Discord uses, so Discord users cannot use Ear Trumpet to change the default output device, they need to use the "Windows Legacy --> Playback Devices" modal

**Comment by riverar** [comment] 2019-12-31 07:46
Thanks @BlueRaja, closing as duplicate of #348. (The shipping version of EarTrumpet doesn't currently support communication device management.)

**Closed by riverar** 2019-12-31 07:46 UTC
Labels: type: feature-request

**Comment by Chaython** [comment] 2024-02-14 22:06
The fork was made, but you guys never merged the functionality? Why?
Would be an excellent feature for me, but obviously the fork was abandoned...

**Comment by Chaython** [comment] 2024-02-22 08:42
As a temporary solution I am using 
https://github.com/frgnca/AudioDeviceCmdlets
and "Set-AudioDevice -Index ?" ? being replaced with the device I want to switch to...
I am using a script to automate this, to switch between my Bluetooth and wired headphones. 
"# Import the AudioDeviceCmdlets module
Import-Module AudioDeviceCmdlets

# Define the indices of the target devices 
$deviceIndex1 = 1
$deviceIndex2 = 2

# Function to toggle between the desired indices
function Toggle-AudioDevices {
    $targetIndex = if ((Get-AudioDevice -Index $deviceIndex1).ID -eq (Get-AudioDevice -Playback).ID) {
        $deviceIndex2 
    } else {
        $deviceIndex1
    }

    Set-AudioDevice -Index $targetIndex
    Set-AudioDevice -Communication -Index $targetIndex

    Write-Host "Default playback and communication devices switched to index $targetIndex"
}

# Toggle playback and communication devices
Toggle-AudioDevices "
