### ISSUE TITLE
Sound settings appear on the wrong monitor

### ISSUE THREAD

**Issue by LordLioath** [File-New-Project/EarTrumpet#1559] opened 2024-06-04 01:41 UTC
### Summary

When clicking on the speaker icon in the taskbar, the flowout window will appear and then move to another window and clip off the screen.

### Steps to reproduce

Click Speaker for Ear Trumpet

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.3672

**Comment by riverar** [comment] 2024-06-28 05:23
@LordLioath That's not good. Is this from a system that was restored from sleep (e.g. laptop) by any chance?

**Comment by riverar** [comment] 2024-11-13 00:21
Closing as duplicate of #1304.

**Closed by riverar** 2024-11-13 00:21 UTC
