### ISSUE TITLE
EarTrumpet lag when moved

### ISSUE THREAD

**Issue by helixxger** [File-New-Project/EarTrumpet#881] opened 2021-07-16 08:46 UTC
## Description
When I try to move the eartrumpet window it starts lagging

https://user-images.githubusercontent.com/76208371/125919788-cfa76078-9ee6-4d18-9985-072b294c48eb.MOV

## Meta
* EalrTrumpet version: 2.1.8.0
* Windows 10 version: 19043.1083

## Screenshots
I'll add a video

**Comment by riverar** [comment] 2021-07-16 08:48
Duplicate of pinned issue #349. Thanks!

**Closed by riverar** 2021-07-16 08:48 UTC
Labels: type: bug
