### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by Ciribomflax** [File-New-Project/EarTrumpet#485] opened 2020-04-09 15:37 UTC
I see the following error message when trying to lauch:

![trumpet_error](https://user-images.githubusercontent.com/5464351/78913138-d66f9800-7a88-11ea-80d2-8cae4b9361bf.jpg)

**Comment by riverar** [comment] 2020-05-07 08:44
Dupe of #227, can you please follow the Feedback Hub steps listed in there and post a link to the feedback item? Thanks!

**Closed by riverar** 2020-05-07 08:44 UTC
