### ISSUE TITLE
Eartrumpet crashes if you are connected via HDMI, switch back to main then back to HDMI

### ISSUE THREAD

**Issue by makedir** [File-New-Project/EarTrumpet#1516] opened 2024-03-02 20:35 UTC
### Summary

Eartrumpet crashes if you are connected via HDMI, switch back to main then back to HDMI.

### Steps to reproduce

Play audio with HDMI audio. Switch monitors so the HDMI signal is lost and the laptop switches back to internal audio. You hear the audio now playing on the laptop speakers. Switch HDMI back, Eartrumpet  crashes.

### EarTrumpet version

2.3.0.0

### Windows version

22631.3155

**Comment by makedir** [comment] 2024-03-04 20:49
Next to the crash comes the issue that Eartrumpet doesnt properly work anymore after a while, mostly in relation with the issue. That the volume slider starts to lag and doesnt move with the mouse anymore together becomes slower and slower and creates 100% cpu usage.

This issue is present since years and was not fixed so far.


https://github.com/File-New-Project/EarTrumpet/assets/6721083/2cb1ccb3-ab35-4ee8-a6eb-f5f8cdef4125

**Comment by makedir** [comment] 2024-03-14 04:29
Restarting EarTrumpet also fixes the issue.

**Comment by makedir** [comment] 2024-04-07 01:04
@riverar Can you please look into this? EarTrumpet is not usable with this bug. It is crashing if you change hdmi connection and usw hdmi audio and the audio vanishes if you change  monitors.

**Comment by riverar** [comment] 2024-04-20 17:37
Will do, let me see if I can reproduce.

**Comment by riverar** [comment] 2024-04-20 17:41
@makedir Can you reproduce this with an EarTrumpet dev build? https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

**Comment by riverar** [comment] 2024-11-13 00:29
Closing in favor of master issue #1305.

**Closed by riverar** 2024-11-13 00:29 UTC

**Comment by makedir** [comment] 2024-11-29 17:53
When will this fix go live in the MS Store? Current version is still crashing all the time.

**Comment by makedir** [comment] 2024-12-01 11:49
How would you install dev build? Dont dev build have logging enabled?

**Comment by riverar** [comment] 2024-12-01 17:06
https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

Has no extra logging, it just sources from the `dev` branch which is much newer.

**Comment by makedir** [comment] 2024-12-01 17:24
Does it auto update after installation when a new dev build comes out?

**Comment by riverar** [comment] 2024-12-01 17:49
Yup. With AppInstaller, the app will check for updates at every launch and if one is available, it is installed at next launch.

**Comment by makedir** [comment] 2024-12-08 00:44
After testing the beta build for a few days I can say the issue is still not fixed. Volume numbers are stuck after the issue for example and wont update anymore. @riverar

**Comment by makedir** [comment] 2024-12-11 15:00
@riverar Please reopen this ticket and fix it. Eartrumpet is unusable because of this issue since years.

**Comment by riverar** [comment] 2024-12-11 16:53
Hey @makedir, this issue was closed because it is linked to master issue https://github.com/File-New-Project/EarTrumpet/issues/1305. That issue is tracking the same root cause. I'll make this priority number one, but progress may be slow due to western holidays.

**Comment by riverar** [comment] 2025-01-08 15:15
Yikes, that's weird. If you get a chance to try it again, maybe we can get a process dump or run Process Monitor to see what's going on. We don't typically write to disk... maybe another process was stuck in a tight audio session creation loop and EarTrumpet was constantly reading the app's info?

**Comment by makedir** [comment] 2025-01-08 15:27
it is connected to the same issue of this thread, caused by if you use HDMI and the monitor switches off/on back and forth eventually Eartrumpet does this.

**Comment by riverar** [comment] 2025-01-08 15:45
We only write to disk (%TEMP%\EarTrumpetTrace.log) if the ALT key was held when starting EarTrumpet. It's a way to debug startup errors. Does that file exist? If not, we have no other writes to disk. Also heads up, Task Manager is showing disk utilization %, not exclusively writes, so the app could be _reading_ too.

**Comment by makedir** [comment] 2025-01-08 15:47
Erm... like I said. It causeed c: to run out of disk space to 0mb free. it was writing to disk. I have uninstalled like I said, caused 4GB to free disk space again.

**Comment by riverar** [comment] 2025-01-08 17:09
Fair enough. Will try to set up a test environment for this; thanks again for reporting and sorry for the headaches.

**Comment by makedir** [comment] 2025-01-08 17:15
Might also be because of that memory leak seen on the picture (1700mb ram usage... why?) it was caused by swap to disk, but normally that should be seen under system in task manager.

**Comment by lastmetroid** [comment] 2026-05-01 14:12
Hello,

could you please implement the feature, that you easily can switch for each
app what audio output device it uses that would be nice.

**Comment by riverar** [comment] 2026-05-01 17:34
@lastmetroid That's already in EarTrumpet; right click an app and click the arrows.
