### ISSUE TITLE
The volume setting of some applications does not stay in memory.

### ISSUE THREAD

**Issue by breatme** [File-New-Project/EarTrumpet#346] opened 2019-04-03 08:18 UTC
Hello,
The volume setting of some applications doesn't stay in memory.

Here is the list of applications that have this problem on my PC:
- discord (Desktop)
- MusicBee (Portable)
- Skype (UWP)

![2019 04 03 001](https://user-images.githubusercontent.com/6360676/55463619-bdbcde80-55f9-11e9-9463-96bd65db6f4d.jpg)

I need to put volume setting of these application at each run of them.

Here my PC : https://fr.msi.com/Laptop/support/GT63-Titan-8RG.html
I use Windows 10 Pro 1809 x64

Regards

**Comment by riverar** [comment] 2019-04-08 05:29
Closing, duplicate of #315 . Thanks! We reported this to Microsoft several times now, will remind them again.

**Closed by riverar** 2019-04-08 05:29 UTC
