### ISSUE TITLE
Add switching Spatial sound please

### ISSUE THREAD

**Issue by avansteenbruggen** [File-New-Project/EarTrumpet#588] opened 2020-12-04 21:21 UTC
It would be great to have the option to instantly switch between spatial sounds (and off)
Now i have to leave the Windows sound property icon on in the tray, just to do that.

**Comment by Cyberdroid1** [comment] 2020-12-21 11:05
Duplicate of #212.

**Closed** 2021-02-17 08:21 UTC
