### ISSUE TITLE
"No playback devices..." after disconnecting headphones

### ISSUE THREAD

**Issue by loldev69** [File-New-Project/EarTrumpet#265] opened 2018-07-12 10:25 UTC
Steps to reproduce on my system:
1 - Open any audio source, I tried with a few games and a few audio and video files opened in VLC
2 - Connect headphones to headphone jack on motherboard, audio will play in headphones instead than on normal speakers as expected
3 - Disconnect headphones, audio will switch back to speakers but EarTrumpet will display "No playback devices" when opened via left click.

Right clicking will show the proper playback devices list, switching between devices with said list will work, the icon will update to show their correct volume level, but the left click menu will still display the bug even after switching devices.
The mixer is not affected by the bug either.

Not a high priority bug for sure, but might help with similar issues, such as #233 or #218 

Here is a log: [earTrumpet.txt](https://github.com/File-New-Project/EarTrumpet/files/2188178/earTrumpet.txt)

**Comment by riverar** [comment] 2018-07-12 17:34
Thanks, perfect repro steps! 👍

**Comment by riverar** [comment] 2018-07-17 10:30
Dupe of #218

**Closed by riverar** 2018-07-17 10:30 UTC
Labels: type: bug
