### ISSUE TITLE
EarTrumpet locking image resources

### ISSUE THREAD

**Issue by gaspardip** [File-New-Project/EarTrumpet#256] opened 2018-07-02 19:42 UTC
Hi, im facing a weird bug with EarTrumpet lately.

Im developing a UWP JS app using VS2017 and, after some time, Visual Studio will just stop compiling the app complaining about one specific resource being used by another process. The message reads:

`Error DEP0500: The folder "C:\Users\<username>\Documents\Visual Studio 2017\Projects\<repo>\<project>\bin\Debug\AppX" could not be deleted. IOException - The process cannot access the file 'Square44x44Logo.scale-200.png' because it is being used by another process. [0x80070020]`

This has happened to me both at my work machine and my personal one.

I had no clue it was EarTrumpet until I searched for the asset being used in [SysInternals' Process Explorer](https://docs.microsoft.com/es-es/sysinternals/downloads/process-explorer), which threw the following results:

`EarTrumpet.exe	27656	File	C:\Users\<user>\Documents\Visual Studio 2017\Projects\<repo>\<project>\bin\Debug\AppX\assets\images\Square44x44Logo.scale-200.png`

`EarTrumpet.exe	27656	File	C:\Users\<user>\Documents\Visual Studio 2017\Projects\<repo>\<project>\bin\Release\AppX\assets\images\Square44x44Logo.scale-200.png`

(notice how both release and debug compilations are affected)

OS Version: 17134.112
VS Version: 15.7.4
EarTrumpet Version: 2.0.3.0

**Comment by mfkl** [comment] 2018-07-09 12:42
Yeah, it actually locked a resource file in the `bin` folder of VS which prevented it to deploy. You should definitely have a look.

**Comment by mplogas** [comment] 2018-07-10 10:36
Jup. Also locks .pri resources.

OS Version 17134.112
 VS.NET 15.7.4
EarTrumpet (Store version): 2.0.3.0

**Comment by riverar** [comment] 2018-07-18 07:10
First fix for this is in https://github.com/File-New-Project/EarTrumpet/commit/ba9b3d17cbaad8a4146a8790f4a6b97038304fb6

We're making a change for .pris too.

**Comment by Acenth** [comment] 2018-08-31 18:05
Was this included in any releases? EarTrumpet is currently blocking apps like the Twitch Desktop app from updating because the file is locked. 100% reproducible on latest release.

**Comment by riverar** [comment] 2018-08-31 18:43
@Acenth 2.0.5 has this fix. Just didn't make our release notes. 😞 Also shot you an email about nailing down a client to test with so we can get this fixed asap.

**Comment by riverar** [comment] 2018-09-01 00:04
This is fixed in 2.0.5, closing the issue.

**Closed by riverar** 2018-09-01 00:04 UTC
Labels: type: bug
