### ISSUE TITLE
Microangelo icon software breaks EarTrumpet icons

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [File-New-Project/EarTrumpet#908] opened 2021-09-16 08:35 UTC
Running EarTrumpet 2.1.8.1 on Windows 10 or Windows 11.

Installing Microangelo On Display (evaluation version here: http://www.impactsoftware.com/filekicker/mod70-3-eval.exe ), an icon modification app which uses Explorer shell APIs causes the icons in EarTrumpet to break:

All the icons in EarTrumper then show like this after the above app is installed:

![image](https://user-images.githubusercontent.com/46422834/133578361-fd85f114-a06e-4dda-975e-fc2a80b0d8a0.png)

As soon as that app is uninstalled, the icons return. When developing Classic Shell Start menu, the same issue was encountered by its developer for the Start menu who described the underlying cause:

Microangelo installs an icon handler shell extension. It replaces the shell interface (IExtractIcon) that gets the icon from a file, but it only does so for the ANSI version IExtractIconA and not for the Unicode version IExtractIconW. So the code for EarTrumpet that gets the icons for apps needs to be updated to look for the ANSI interface as well, if the Unicode is not found. This will ensure the icons are no longer broken in EarTrumpet due to this particular issue.

Let me know if you know any more information on reproducing the issue.

P.S. The icons in the Windows 10 and Windows 11 Start Menus also break because of this app, but not in the Windows 7 or XP Start menu.

**Comment by riverar** [comment] 2021-09-16 11:35
I can't reproduce this on Windows 11. Do I need to do something after install?

Looking at MODIcon.dll internals, it does only _implement_ IExtractIconA but that shouldn't be an issue. We don't directly extract icons.

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-16 14:43
Oh ok then EarTrumpet works differently and maybe a different fix is needed.

No, here I was able to repro on Windows 10 1803 as well as Windows 11 22458.1000 just by installing the third party app, made sure Explorer.exe and then EarTrumpet were both restarted after installing the app. The icons for Win32 apps in EarTrumpet stop showing immediately. UWP app icons show correctly. The Movies & TV app icon shows but Windows Media Player doesn't in Windows 11 - just tried.

As soon as this Microangelo app is uninstalled, and again I log off and login again, Win32 app icons show correctly in EarTrumpet.

Sorry if my earlier repro instructions were unclear.

**Comment by riverar** [comment] 2021-09-21 07:19
I can reproduce this but not sure what we can do about it. Microangelo installs a poorly built icon handler.

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-21 08:13
Yes that's true - it is poorly built. It breaks Windows 10/11 Start menu icons too. Its owners should actually update it for Unicode. It's abandonware now but it's the only app I know that has an icon handler for any file type and lets me customize with right click -> Appearance, including 16-bit EXEs for which the Explorer shell removed the code to show icons since Vista. It also handles UAC elevation correctly so customizing icons is easy.

**Comment by riverar** [comment] 2021-09-21 17:03
Thanks for reporting this! Going to close this for now as there's nothing actionable here but I will keep thinking about this.

**Closed by riverar** 2021-09-21 17:03 UTC
Labels: type: third-party-bug
