### ISSUE TITLE
Throws "Incorrect Paremeter" error after  lauching  the app(installed from windows store)

### ISSUE THREAD

**Issue by Dsujan** [File-New-Project/EarTrumpet#321] opened 2018-12-23 08:13 UTC
![capture](https://user-images.githubusercontent.com/25095423/50381932-35a27100-06bb-11e9-9901-c5c4867bd127.JPG)

I have OS Build 17134.472

**Comment by riverar** [comment] 2019-01-11 03:19
[Dupe of #286, thanks for the report.]

Can you please do the following so we can gather trace data?

1. Open Feedback Hub
2. Click Report a Problem and use the data below to populate the fields:
* Title: Issue 286/321 - Incorrect Parameter
* Body: Link to the GitHub issue, mention EarTrumpet
* Category: Problem / Install and Update / App launch issues”
3. Submit

Thanks!

**Closed by riverar** 2019-01-11 03:19 UTC
