### ISSUE TITLE
every audio destination is open when you left click on the icop

### ISSUE THREAD

**Issue by di00ib** [File-New-Project/EarTrumpet#1220] opened 2022-09-06 00:10 UTC
### Summary

kind of hard to find the exact words to describe what I'm having an issue with. So, I'll explain best I can and attack a pic to show you where I'm stuck.
I left clicked to open the volume sliders like normal a few days ago. The normal list of volume sliders popped up. There's a little drop down arrow next to the name of the device that the audio is outputting to. Like the bluetooth speaker, hdmi out, wireless headphones, etc...
I clicked that arrow which showed all of the outputs and their respective volume sliders.
Now I have a big issue.
Left clicking the icon ONLY brings up the full list of sliders for every device output. There's no way to go back to the single output.
The dropdown arrow to go back to normal is gone.
I'm stuck with this giant list that covers the right 1/5 of the screen. I have enough output devices that there's a scroll/slider on the right. 
On top of that, if I don't position my mouse in just the right place, scrolling my mouse wheel scrolls the volume up or down on the slider I'm closest to. I'm messing up my settings on accident trying to get to a different device that I need to scroll to.
Attaching a screenshot to show what I'm talking about.
I've gone so far as uninstalling and reinstalling to no avail.
Any help would be greatly appreciated as I'm stuck with Windows 11.
It worked just fine until I clicked that down arrow.
Every other thing about EarTrumpet works great.
It's 1000% better than the volume system provided for Windows by Microshaft.
Any help would be greatly appreciated.

### Steps to reproduce

I clicked that arrow which showed all of the outputs and their respective volume sliders.
Now it's stuck open and I can't go back to the normal single output device.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.22621.382

### Additional information

![eartrumpet slider issue](https://user-images.githubusercontent.com/51838500/188522525-b69ea321-7270-44c7-a5a4-c576a6a7cb90.png)

a screenshot of what I'm stuck with

**Comment by riverar** [comment] 2022-09-06 01:32
I believe this was just fixed in our `dev` branch. Is your Taskbar also configured to auto-hide?

**Comment by di00ib** [comment] 2022-09-06 03:39
it is set to auto-hide

**Comment by riverar** [comment] 2022-09-06 04:20
Cool. Duplicate of #1206.

If you would like a fix now, you can grab a dev build (see https://eartrumpet.app/). Or I'll prepare a release soon and push it out through the Microsoft Store.

**Closed by riverar** 2022-09-06 04:20 UTC

**Comment by di00ib** [comment] 2022-09-06 08:23
moved to that other #1205 thread you mentioned

**Comment by di00ib** [comment] 2022-09-06 19:30
if you like I'll delete my original post since it's been handled already in
that other thread
