### ISSUE TITLE
Feature Request: Duplicate Audio Source

### ISSUE THREAD

**Issue by SmilerRyan** [File-New-Project/EarTrumpet#625] opened 2021-01-29 23:29 UTC
Within the application, we can currently move audio streams between devices, however an option to duplicate (play on source and destination) would also be very helpful.

One common use for me is to route my microphone through a [Virtual Audio Cable](https://vb-audio.com/Cable/) along with the game audio.
This does work and output both as a single input microphone, however I cannot hear the output of the game itself without also hearing myself.

Having the ability to route directly from within EarTrumpet itself would be a great way to solve this problem.
By duplicating the source though to another device, we can still hear the game, though the destination (the cable) can as well.

Here is another competing open-source program called [audio-router](https://github.com/audiorouterdev/audio-router) that has this functionality, though it's software is buggy, and would be a great addition to here.

Here's a screenshot showing how the duplication could be cancelled (an X next to the duplicate icon), without on the source to duplicate.
![image](https://user-images.githubusercontent.com/14893385/106337667-abf60200-6289-11eb-8ef5-f044459e09fd.png)

**Comment by riverar** [comment] 2021-02-03 05:27
Related: #486

**Comment by riverar** [comment] 2021-02-03 05:55
Going to close as a dupe of #634 (just moved all feature features to this new discussions area), please upvote!

**Closed by riverar** 2021-02-03 05:55 UTC
