### ISSUE TITLE
Volume of Bluestack will reset after closing it

### ISSUE THREAD

**Issue by Ansem93** [File-New-Project/EarTrumpet#432] opened 2019-10-20 11:26 UTC
Hi,
I use Bluestack on my PC. I setted the volume at 10% with earTrumpet, but if I close and reopen it will return to 100%.

There is some way to save the volume of an application for when I close and open it?

**Comment by riverar** [comment] 2019-10-21 18:40
We'll have something to solve this problem soon. Closing as dupe of #23 and #28.

**Closed by riverar** 2019-10-21 18:40 UTC
