### ISSUE TITLE
No option to move audio session...

### ISSUE THREAD

**Issue by idjmic** [File-New-Project/EarTrumpet#385] opened 2019-06-14 02:10 UTC
Just reformatted windows 10 on gaming pc for streaming, wanting to send browser audio to just my headphones and not the live stream... was working! But after setting everything back up there's no option to move the audio session to a different output.  Anyone else? Ideas?

**Comment by davuxcom** [comment] 2019-06-14 06:12
What version of Windows did you install?  Moving sessions requires build 17134 RS4 or higher, make sure you have installed updates.

**Comment by riverar** [comment] 2019-06-14 06:59
Dupe of #323. If you continue to have trouble, please re-open.

**Closed by riverar** 2019-06-14 06:59 UTC

**Comment by idjmic** [comment] 2019-06-14 15:45
WOW! Yes it was that easy, simple update did it.

Mike
