### ISSUE TITLE
Dragging the settings box has a slow-motion animation

### ISSUE THREAD

**Issue by Cyberdroid1** [File-New-Project/EarTrumpet#543] opened 2020-08-15 15:41 UTC
Steps to reproduce - 

1)Open the settings for EarTrumpet by rightclicking on its icon in windows notification area, and choosing settings.
2)Click and hold the title bar and drag it.

Expected result - 
The box should move smoothly with cursor and quickly.

Actual result - 
The box moves slowly and seems vague.

**Comment by riverar** [comment] 2020-08-15 18:53
Thanks, this is a dupe of #349.

**Closed by riverar** 2020-08-15 18:53 UTC
