### ISSUE TITLE
Some features about EarTrumpet

### ISSUE THREAD

**Issue by Gaoyifei1011** [File-New-Project/EarTrumpet#616] opened 2021-01-16 04:21 UTC
1.目前Win10预览版的声音设置直接定位到设置里面的声音选项了，但是EarTrumpet里面的声音设置却是定位到控制面板里面的声音设置，希望可以未来可以定位到设置里面的声音设置
At present, the sound Settings in the preview version of Win10 are directly located to the sound options in the Settings, but the sound Settings in EarTrumpet are located to the sound Settings in the control panel. I hope it can be located to the sound Settings in the Settings in the future
![image](https://user-images.githubusercontent.com/49179966/104796716-c3e27600-57f3-11eb-9d9e-60f1321b347e.png)
![image](https://user-images.githubusercontent.com/49179966/104796779-410deb00-57f4-11eb-8b15-c1f2a06d8223.png)
2.目前微软及第三方的其他应用都已经采用了Fluent Design体系了，希望未来的EarTrumpet也可以采用Fluent Design体系，采用圆角设计，并为设置面板添加一些窗口动画
Fluent Design has already been adopted by Microsoft and other third-party applications, and it is hoped that in the future, Fluent Design can also be adopted for EarTrumpet, with a rounded corner Design and some window animation for the setting panel
EarTrumpet设置面板
EarTrumpet setting panel
![image](https://user-images.githubusercontent.com/49179966/104796835-acf05380-57f4-11eb-81cf-e062aaf5df76.png)
图标希望可以换一个Fluent UI的图标（带有颜色的，不是纯黑白色），并且图标太大了，同时应用下面也没有显示出名称
I wish I could replace the Fluent UI icon (with color, not pure black and white), and the icon is too big, and the name is not displayed under the app
![image](https://user-images.githubusercontent.com/49179966/104796890-196b5280-57f5-11eb-9362-fe9823a01149.png)
3.一些地方没有翻译出来，希望可以翻译到其他语言
Some places are not translated, hopefully it can be translated into other languages
在这些地方，中文被翻译为“无”，但在中文界面下这里只是显示出“None”
In these places, Chinese is translated as "无", but in the Chinese interface it just shows "None".
![image](https://user-images.githubusercontent.com/49179966/104796903-3738b780-57f5-11eb-85c5-e0293b6c1952.png)

**Comment by riverar** [comment] 2021-02-03 06:03
Thanks @Gabboxl!

1. Duplicate of https://github.com/File-New-Project/EarTrumpet/issues/554, fixed in the next update
2. Duplicate of https://github.com/File-New-Project/EarTrumpet/issues/484, fixed in the next update (let us know if it needs more work)
3. That looks like a good bug, might be in the OS itself. Will require investigation.

**Closed** 2021-02-03 06:05 UTC
