### ISSUE TITLE
Application stuck on an audio that has been disabled/disconnected

### ISSUE THREAD

**Issue by ArsenicBismuth** [File-New-Project/EarTrumpet#1194] opened 2022-07-12 23:08 UTC
### Summary

Sometimes (not to all device) you need to disconnect an audio device (or even the driver automatically switches between 2-3 devices). The problem arise when you have already set the device for certain apps, and that device is disconnected. Now you have now way to change its device from EarTroumpet, and yet you also won't hear its sound anywhere.

The only workaround was:

1. Disable everything that's disconnected.
2. Restart the app.
3. Sometimes it works, but sometimes it doesn't.

Suggestions:

- A reset setting to remove all device assignments.
- Auto assigning an app assigned to a disabled device, to an enabled one.

### Steps to reproduce

1. Set App X to a certain device 2.
2. Disconnect device 2 (not disabling it).
3. App X is now stuck to a now hidden device 2.
4. No sound is coming out from App X.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.1806

### Additional information

This might only happen on very specific setup, where 1 sound device switch between 3 different instances (below you can see it). GST56-DP is an external monitor connected to a USB-C w/ Display Port, and every time I reconnect it, it'll randomly pick 1 out of the three and mess up EarTroumpet.

![image](https://user-images.githubusercontent.com/19264532/178613197-549ccc7f-e837-4ddb-a8b3-efbf949005b7.png)

**Comment by riverar** [comment] 2022-08-21 04:10
When we redirect audio, we use an API in the OS to do so. Windows _should_ be handling these scenarios, but sometimes it gets stuck.

Type `Win+X`, select Settings, then go to System > Sound > App volume and device preferences (or Volume mixer on Windows 11). At the bottom of this page, click the Reset button to fix your issue.

Closing as a duplicate of #403 but I'll take another look to see if there's anything we can improve here.

**Closed by riverar** 2022-08-21 04:10 UTC
Labels: type: windows-bug
