### ISSUE TITLE
Sometimes the flyout doesn't close and the flyout animation is laggy

### ISSUE THREAD

**Issue by mehraanakbarii** [File-New-Project/EarTrumpet#1367] opened 2023-05-11 12:26 UTC
### Summary

Sometimes the flyout doesn't close and the flyout animation is laggy

### Steps to reproduce

I think you should know it better.

### EarTrumpet version

Latest

### Windows version

Latest Windows 10 22H2

**Comment by riverar** [comment] 2023-05-11 15:09
We're aware, it's a limitation currently due to the acrylic effect used in that flyout and the UI technology we're using.

Closing as duplicate of #936 for now.

**Closed by riverar** 2023-05-11 15:09 UTC
