### ISSUE TITLE
Two EarTrumpet tray icons after waking up from sleep or hiberation

### ISSUE THREAD

**Issue by martinsstuff** [File-New-Project/EarTrumpet#404] opened 2019-08-10 18:17 UTC
![image](https://user-images.githubusercontent.com/29005772/62825418-3bc95d00-bb79-11e9-9c51-dd9b09817428.png)

Installed via Microsoft Store.

Started happening recently, possibly related to "Fixed tray icon disappearing when the Windows Shell crashes/restarts" in 2.1.4.0?

Edit: Right clicking any of the icons and selecting "Exit" closes both, opening EarTrumpet again correctly displays only one icon.

**Comment by davuxcom** [comment] 2019-08-10 18:29
If you hover over each icon, does it continue to stay there, or does one of them disappear at that point?

**Comment by davuxcom** [comment] 2019-08-10 18:53
If possible (I'm assuming but haven't confirmed yet this repro's frequently with hibernation and no other factors) can you `Settings -> General -> About -> Collect troubleshooting data` and share it?  The specific error code will be interesting.

**Comment by wcgriffyn** [comment] 2019-08-15 03:14
I can confirm the bug. I have the Windows sound icon disabled, and the Ear Trumpet icon enabled. After waking the computer from sleep, there is an additional icon in the system tray. For each additional sleep, wake cycle another icon appears in the try.

![Annotation 2019-08-14 230810](https://user-images.githubusercontent.com/22209212/63070382-f85c4f00-bee8-11e9-95fe-f676045b270c.png)

Here is the troubleshooting data from Ear Trumpet:
[tmpEE9F.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/3504192/tmpEE9F.tmp.txt)

**Comment by MahdiGhiasi** [comment] 2019-08-15 16:04
I've also seen this recently a couple times.

**Comment by davuxcom** [comment] 2019-08-15 21:21
@wcgriffyn If you continue to see this regularly, could you please do the wake/hibernate cycle and then very quickly after the second icon appears export the EarTrumpet log?  Your log has the past hour or so but the key events aren't there as expected.

We think we understand the issue but were unable to reproduce locally.

**Comment by martinsstuff** [comment] 2019-08-16 18:14
Interestingly I haven't had this happen since I opened this issue even after rebooting on multiple occasions and sleeping/hibernating for varying amounts of time (I didn't do anything to fix it after that, it just stopped happening).

However I had #407 happen a few times, I'll keep an eye in that and also try to post logs when/if it happens again.

**Comment by MahdiGhiasi** [comment] 2019-08-16 20:53
I just noticed that what I experience about this issue has a slight difference with what described in the first post. When the second EarTrumpet icon appears, click/right-click on either of the icons does nothing. (clicking on it does not open the volume pane and right clicking on it does not open the context menu)

**Comment by wcgriffyn** [comment] 2019-08-17 03:13
> @wcgriffyn If you continue to see this regularly, could you please do the wake/hibernate cycle and then very quickly after the second icon appears export the EarTrumpet log? Your log has the past hour or so but the key events aren't there as expected.
> 
> We think we understand the issue but were unable to reproduce locally.

I've attached a log from right after the PC wakes.

[2019-08-16 tmpC90D.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/3511609/2019-08-16.tmpC90D.tmp.txt)

**Comment by SilentPrayeCG** [comment] 2019-08-20 01:05
I had up to three icons 
![image](https://user-images.githubusercontent.com/17825684/63309375-fc84d400-c30f-11e9-8385-e9978290ad4c.png)
all of them functional

first debug file after some time after sleep, second one (log2.txt) immediately after sleep

[tmp9D2F.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/3518187/tmp9D2F.tmp.txt)
[log2.txt](https://github.com/File-New-Project/EarTrumpet/files/3518206/log2.txt)

probably if i sleep one more time it will create another one

i thought it have something to do with Bluetooth headphones, but i didn't connected it to USB this time and it still created another icon

i don't know if it related, but i also sometimes have bug when icon disappear at all, (but i guess recently i had only duplicates bug), while process was active, and to resurrect icon i was forced to kill process and restart it.

**Comment by martinsstuff** [comment] 2019-08-25 04:24
Here is the relevant part of the log file from when it happened to me just now:

```
00:20:49.248 UI ShellNotifyIcon Update NIM_MODIFY Failed: 1460
00:20:49.250 UI ShellNotifyIcon Update NIM_ADD Failed (first attempt) 1008
00:20:49.266 UI ### ShellNotifyIcon Update NIM_ADD Failed: 1008 ###
00:20:49.266 UI ShellNotifyIcon Update NIM_SETVERSION Failed: 1460
00:20:49.816 UI WindowsTaskbar Current: Location=Left, AutoHide=False, Taskbar=854730, Size=[Left=0,Top=0,Right=107,Bottom=1440], Monitor=Screen[Bounds={X=0,Y=0,Width=3440,Height=1440} WorkingArea={X=107,Y=0,Width=3333,Height=1440} Primary=True DeviceName=\\.\DISPLAY5
00:20:52.291 UI WindowsTaskbar Current: Location=Left, AutoHide=False, Taskbar=854730, Size=[Left=0,Top=0,Right=107,Bottom=1440], Monitor=Screen[Bounds={X=0,Y=0,Width=3440,Height=1440} WorkingArea={X=107,Y=0,Width=3333,Height=1440} Primary=True DeviceName=\\.\DISPLAY5
00:20:57.618 UI ShellNotifyIcon Update NIM_MODIFY Failed: 2147500037
00:21:05.074 UI ShellNotifyIcon ShowContextMenu
00:21:05.160 UI ShellNotifyIcon ContextMenu.Opened
00:21:06.888 UI SettingsWindow .ctor
00:21:07.093 UI ShellNotifyIcon ContextMenu.Closed
```

**Comment by riverar** [comment] 2019-08-25 04:27
Thanks @martinsstuff we're working on this right now.

**Comment by BreadBreadington** [comment] 2019-08-26 12:06
![3JHcrID 1](https://user-images.githubusercontent.com/32611147/63689623-cb475f00-c84d-11e9-802b-5f0f5c9e5997.png)

What do I win

**Comment by TheEssem** [comment] 2019-09-22 02:19
I'm having the same issue, [here's my log.](https://gist.github.com/TheEssem/85eb591f6eb7478370095228a5747f40)

Also, @BreadBreadington, those are rookie numbers. ;)

![NZVeKpsiq8](https://user-images.githubusercontent.com/21112968/65381364-2a658b80-dcb5-11e9-986f-859f4f65c288.png)

**Comment by nimand** [comment] 2019-10-21 01:19
Is any more data needed? I have this issue pretty consistently.

**Comment by furx** [comment] 2019-11-08 20:46
What's the status on this? To this day I am experiencing this issue. :)

**Comment by riverar** [comment] 2019-11-11 04:37
No additional data needed, we're working on it! It's a complex problem that involves both the Windows Shell and EarTrumpet.

**Comment by ElvenSpellmaker** [comment] 2019-11-27 11:00
I also have two icons, and they're both not the same in their tooltip:
![image](https://user-images.githubusercontent.com/2286713/69717988-18fd8d00-1105-11ea-8906-491c19bdfe09.png)
![image](https://user-images.githubusercontent.com/2286713/69717979-1438d900-1105-11ea-9d44-be42706bc120.png)

**Comment by Taomyn** [comment] 2019-11-29 06:00
I'm having this also, but for me the most annoying is that when I re-run the icon appears at the start of the icons so I have to keep dragging it back to the far right where I want.

Hope you find the cause soon.

**Comment by riverar** [comment] 2019-11-29 07:53
We're aware of the cause (see https://github.com/File-New-Project/EarTrumpet/issues/404#issuecomment-552290070) bear with us, should be fixed in the next update.

**Comment by MammothJerk** [comment] 2020-01-11 11:58
I'm also still running into this issue every so often

**Comment by CoreParadox** [comment] 2020-01-30 20:25
> We're aware of the cause (see [#404 (comment)](https://github.com/File-New-Project/EarTrumpet/issues/404#issuecomment-552290070)) bear with us, will be fixed in the next update.

Sorry to bump an old thread, is there a timeframe for this next release, or is it easy enough that I can build it from source?

**Comment by riverar** [comment] 2020-01-30 20:44
@CoreParadox Sadly I have to perform a localization pass and add a now-required privacy policy link to the Settings area, otherwise Microsoft Store will reject the next update. This has slowed down update release.

We have compilation documentation for EarTrumpet, it's relatively easy. https://github.com/File-New-Project/EarTrumpet/blob/master/COMPILING.md

**Comment by riverar** [comment] 2020-05-07 09:33
Closing, fixed.

**Closed by riverar** 2020-05-07 09:33 UTC
Labels: status: fixed in next update, type: bug
