### ISSUE TITLE
Audio Doesn't Switch Sources for Final Fantasy 14

### ISSUE THREAD

**Issue by Doxmia** [File-New-Project/EarTrumpet#205] opened 2018-06-13 16:44 UTC
This is probably too specific for you guys to care about; but when I saw this release I dropped everything and updated my Windows to the latest release to get this installed because of the source switching feature.

Unfortunately it doesn't appear to work in the game Final Fantasy 14. It's a bit of a pain to install and test yourself but they do offer a free trial. I imagine if it doesn't work in Final Fantasy 14 there's probably other games/apps that might run into the same issue.

When I try to switch it just remains listed under the current selected audio source and continues playing through that audio source. Other apps switch that I have tested so far, though. #

**Comment by riverar** [comment] 2018-06-13 17:34
Not too specific at all, will try to root cause this now. Thanks!

**Comment by riverar** [comment] 2018-06-14 07:44
Sadly not a lot we can do here. Final Fantasy XIV is dropping the redirect request. The Windows sound mixer can't redirect this audio either. Will send a note to Square Enix.

```  FINAL FANTASY XIV
  FINAL FANTASY XIV
    [Active]: 22% Desktop pid:26240 
    AppId: D:\games\ffxiv\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\trial\ffxiv_dx11.exe  id={0.0.0.00000000}.{861975b6-779d-4316-a50e-f4c8d8eec75f}|\Device\HarddiskVolume1\games\ffxiv\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\trial\ffxiv_dx11.exe%b{00000000-0000-0000-0000-000000000000}|1%b26240
    IconPath: D:\games\ffxiv\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\trial\ffxiv_dx11.exe
    GroupingParam: 4d4352aa-6982-4cd2-a10c-76dc0aaf393e
    Persisted Playback Endpoint: {0.0.0.00000000}.{80927fc2-1b82-4ece-b92b-6b961a065a64}```

**Comment by riverar** [comment] 2018-06-14 07:57
Filed support ticket with Square Enix (`8536302`). Will update if I hear back.

**Comment by riverar** [comment] 2020-05-07 09:32
@Doxmia Are you still playing FFXIV? Is this still an issue? Square Enix never returned our email.

**Comment by Doxmia** [comment] 2020-05-07 15:06
I am, yes. With their latest expansion they started supporting switching audio source in Windows natively without having to restart the game. TBH I’ve been using VoiceMeter for awhile now so haven’t personally tested it again.
  

  
  
  

  
  
>

**Comment by Squall-Leonhart** [comment] 2021-12-03 14:15
Endwalker just removed this ability, they went back to using their poor xaudio 2.7 implementation that hasn't got notification events implemented.  up till recently they implemented xaudio in 2 helper libraries that were loaded depending on the users OS.

**Comment by mmonaghan** [comment] 2021-12-08 17:34
As an interesting note, since Endwalker it is still possible to redirect audio through EarTrumpet if every time you launch the game you manually re-assign it to your desired device, the only issue I currently face is that whatever they changed with the expansion has caused it to always force itself to system default audio device on startup, and then allow redirections later. 

Any ideas as to whether it'd be possible to add application-specific delays before sending redirection requests? Or how to otherwise automate the re-assignment of audio device every time the game is launched?

**Comment by riverar** [comment] 2023-01-26 20:59
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Thanks!

**Closed by riverar** 2023-01-26 20:59 UTC
Labels: type: third-party-bug
