### ISSUE TITLE
Age of Empires III Definitive, Ultimate Admiral Dreadnoughts not appearing in EarTrumpet

### ISSUE THREAD

**Issue by SupermanIAm** [File-New-Project/EarTrumpet#611] opened 2021-01-08 17:40 UTC
I have looked through everything and can't find a similar problem.  I have now two games where once opened, they are not showing as active in order to change the sound source.  In the attached photos you can see ultimate admiral Dreadnoughts active in task manager as build.exe, and it also is doing the same thing for AoE3 Definitive addition.  The program is listed in legacy sound mixer as shown in the third screen shot.

![image](https://user-images.githubusercontent.com/77167144/104046487-2d3c0680-51ae-11eb-9930-9ed5e1dc27bd.png)
![image](https://user-images.githubusercontent.com/77167144/104046624-5a88b480-51ae-11eb-8907-02b98eea090c.png)
![image](https://user-images.githubusercontent.com/77167144/104046780-991e6f00-51ae-11eb-8aa2-fc3271020f19.png)

**Comment by dazzknowles** [comment] 2021-01-19 13:04
I had similar, Chrome either doesn't show or disappears when moved to a different sound source so then it can't be moved or managed again without closing it and opening Ear Trumpet again.

**Comment by SupermanIAm** [comment] 2021-01-19 13:22
I actually accidentally solved the problem.   Turning on spatial sound resulted in all the missing applications showing up.

**Comment by riverar** [comment] 2021-02-15 01:43
@SupermanIAm That certainly shouldn't be necessary. Does it disappear again when spatial audio is turned off?

**Comment by riverar** [comment] 2021-02-15 02:00
⚠ Cannot reproduce with UA:D 
![image](https://user-images.githubusercontent.com/475132/107897667-835b4280-6eee-11eb-922a-9a1aeb1653af.png)

**Comment by riverar** [comment] 2021-02-24 08:39
Pinging @SupermanIAm is this still an issue?

**Comment by dazzknowles** [comment] 2021-02-24 09:15
For me, it hasn't been an issue since enabling spatial sound as per @SupermanIAm's suggestion.

**Comment by riverar** [comment] 2023-01-26 21:09
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 21:09 UTC
Labels: status: can't reproduce
