### ISSUE TITLE
Suggestion: Allow dragging apps between playback devices

### ISSUE THREAD

**Issue by LRitzdorf** [File-New-Project/EarTrumpet#569] opened 2020-10-16 04:37 UTC
While EarTrumpet is an excellent piece of software and a great improvement over Windows' built-in volume UI, one aspect in particular sticks out as annoyingly complicated.

In order to move an app's audio to a different playback device, the user must open the EarTrumpet flyout, right-click the app in question, click the double-arrow "switch" button, and choose the new device to use. This flow would be greatly simplified if the user could simply drag the app's entry (on the flyout's main screen) into the area below the desired playback device.

**Comment by riverar** [comment] 2020-11-11 07:28
Thanks @LRitzdorf, going to tag this as a dupe of #229 and close.

**Closed by riverar** 2020-11-11 07:28 UTC

**Comment by LRitzdorf** [comment] 2020-11-11 15:29
Ah, my mistake! I didn't see that issue. Thanks!
