### ISSUE TITLE
Audio levels set in Windows modern sound mixer reset upon app/session restart

### ISSUE THREAD

**Issue by YWI** [File-New-Project/EarTrumpet#315] opened 2018-12-14 08:15 UTC
Hello,

I use ear trumpet every day but I have an issue where it didn’t happen until a month or two ago.
I used to be able to set audio levels and after restarting my PC or the application the audio levels remain the same but now whenever I restart the application or my pc the audio levels reset to 100% and then I have to put them back to my desired levels. 

For example, I set them to https://ywi.cloud/i/ZPycArmnL.png
Then I restart they return to https://ywi.cloud/i/B7PlfDi9u.png

It's really tiring to put the audio levels all again every time I restart the application or my entire pc.
Please help me resolve my issue. I have had multiple tickets most of them become inactive and no one helps, I really hope this ticket can receive attention into it.

**Comment by riverar** [comment] 2018-12-16 09:53
Hey @YWI we can reproduce this. I've sent an email to the audio team at Microsoft to figure out what's going on. (It's the holiday season so don't expect anything quickly.) FYI: We will also have a future EarTrumpet version that will address this gap.

**Comment by YWI** [comment] 2018-12-16 10:02
This is nothing but great news. Thank you for your support and quick work put in into the resolution of this bug. I hope you can reply to this ticket once the issue has been resolved.

I wish you great holidays!

- YWI

________________________________

**Comment by YWI** [comment] 2019-01-24 14:37
Hello again,

Is there any updates on this issue. I hope a resolution can be worked on soon.


Best Regards,
Ward Alissa || YWI

________________________________

**Comment by Witchodox** [comment] 2019-01-29 16:43
I was having the same issue and found [this post](https://www.reddit.com/r/techsupport/comments/4h9vjt/) on reddit. Their solution worked for me.

**Comment by YWI** [comment] 2019-01-29 16:45
> I was having the same issue and found [this post](https://www.reddit.com/r/techsupport/comments/4h9vjt/) on reddit. Their solution worked for me.

How exactly do I add a registry can you please help me on skype/discord. I've been trying to find a solution for around 3 months.

**Comment by Witchodox** [comment] 2019-01-30 23:23
Search for **regedit** with Windows Search and this should show up:
![regedit](https://user-images.githubusercontent.com/43663803/52018910-acb9f900-24f4-11e9-9fe6-d999abfd6198.PNG)
Open it and Windows will ask you if you want to allow it to make changes to your device. Answer **Yes**.
Now you have to navigate to HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\
![hkey_current_user](https://user-images.githubusercontent.com/43663803/52019148-906a8c00-24f5-11e9-8e88-573b5018db54.PNG)
![hkey_current_user_software](https://user-images.githubusercontent.com/43663803/52019153-93657c80-24f5-11e9-8a18-a51bcd6d20c9.PNG)
When you find it right click the Internet Explorer key (the thing that looks like a folder) and hover over **New** and select **Key**.
![new_key](https://user-images.githubusercontent.com/43663803/52019074-5305fe80-24f5-11e9-94d7-dd3b328d4775.PNG)
Name the key **LowRegistry**.
Now add a key named **Audio** to **LowRegistry**.
Then add a key named **PolicyConfig** to **Audio**.
Then add a key named **PropertyStore** to **PolicyConfig**.
And then you're done. It should look like this:
![done](https://user-images.githubusercontent.com/43663803/52019459-78473c80-24f6-11e9-96cb-f6cc1a98f2fe.PNG)
You may need to restart your computer before the changes work.

**Comment by riverar** [comment] 2023-01-26 21:03
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (Windows is supposed to remember app audio volumes.) Feel free to keep the discussion going. Thanks!

**Closed by riverar** 2023-01-26 21:03 UTC
Labels: type: windows-bug

**Comment by Ryflick** [comment] 2024-03-13 22:58
> Search for **regedit** with Windows Search and this should show up: ![regedit](https://user-images.githubusercontent.com/43663803/52018910-acb9f900-24f4-11e9-9fe6-d999abfd6198.PNG) Open it and Windows will ask you if you want to allow it to make changes to your device. Answer **Yes**. Now you have to navigate to HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer ![hkey_current_user](https://user-images.githubusercontent.com/43663803/52019148-906a8c00-24f5-11e9-8e88-573b5018db54.PNG) ![hkey_current_user_software](https://user-images.githubusercontent.com/43663803/52019153-93657c80-24f5-11e9-8a18-a51bcd6d20c9.PNG) When you find it right click the Internet Explorer key (the thing that looks like a folder) and hover over **New** and select **Key**. ![new_key](https://user-images.githubusercontent.com/43663803/52019074-5305fe80-24f5-11e9-94d7-dd3b328d4775.PNG) Name the key **LowRegistry**. Now add a key named **Audio** to **LowRegistry**. Then add a key named **PolicyConfig** to **Audio**. Then add a key named **PropertyStore** to **PolicyConfig**. And then you're done. It should look like this: ![done](https://user-images.githubusercontent.com/43663803/52019459-78473c80-24f6-11e9-96cb-f6cc1a98f2fe.PNG) You may need to restart your computer before the changes work.

Woah, thank you so much!
Up until now in 2024 I had this issue few days ago. Did fresh install Windows 10 and my audio keeps resetting. 

After I tried your solution it works like a charm! Thanks!
