### ISSUE TITLE
Please add a global volume selector

### ISSUE THREAD

**Issue by sibbl** [File-New-Project/EarTrumpet#21] opened 2015-08-01 10:26 UTC
I'd love to have only one icon in my sys tray to control both the global sound volume as well as specific apps.

**Comment by foxx1337** [comment] 2015-08-01 11:06
I second this. There's also the need to add multiple sliders, one for each "active" sond adapter in the system.

**Comment by vbandi** [comment] 2016-04-09 22:51
+1

**Comment by GoldenTao** [comment] 2016-04-10 22:55
Duplicate of #10

**Closed by GoldenTao** 2016-04-10 22:55 UTC
Labels: enhancement
