### ISSUE TITLE
Incorrect display when scaling 

### ISSUE THREAD

**Issue by DarkTemplar2012** [File-New-Project/EarTrumpet#1409] opened 2023-07-08 14:39 UTC
### Summary

Windows 11 set the custom scaling to 110 percent. The tray icon does not display well
![Снимок экрана 2023-07-08 203836](https://github.com/File-New-Project/EarTrumpet/assets/39565767/03cc630d-902f-494a-a964-56f030685d35)

### Steps to reproduce

Windows 11 set the custom scaling to 110 percent. The tray icon does not display well

### EarTrumpet version

2,2,2,2,0

### Windows version

22621.1928

**Comment by riverar** [comment] 2023-07-08 15:31
Duplicate of https://github.com/File-New-Project/EarTrumpet/issues/495. We use a system provided icon but I'll double-check the behavior on Windows 10 and see if there's anything we can glean there. (Windows 11 uses a scalable font glyph instead of an icon.)

**Closed** 2023-07-08 15:32 UTC
