### ISSUE TITLE
Volume Flickering

### ISSUE THREAD

**Issue by DracoClaw** [File-New-Project/EarTrumpet#427] opened 2019-10-06 12:14 UTC
when i drag a app to 0 it starts flickering between 0 but on, and muted. Even putting the volume back up does not fix it.

**Comment by DracoClaw** [comment] 2019-10-06 12:16
closing out of the app that is flickering works, but ending eartrumpet does not.

**Comment by riverar** [comment] 2019-10-21 18:34
Hi @DracoClaw, can you name the app? Sounds like it's not handling external audio level changes correctly and/or the mute state.

**Comment by DracoClaw** [comment] 2019-10-22 00:21
yeah, its the new xbox app

**Comment by riverar** [comment] 2019-10-22 03:36
@DracoClaw There's quite a few Xbox apps now. I can't reproduce with Xbox Console Companion, is that the one? Got a screenshot?

**Comment by DracoClaw** [comment] 2019-11-04 15:02
Its the one for the Xbox Game Library. I think its called Xbox (Beta)

**Comment by martinsstuff** [comment] 2019-12-01 21:59
I can confirm I have a similar issue as well, however for me the situation is that whenever my volume slider reaches 0 and it switches into muted it starts "flickering"/toggling the mute button at a seemingly random frequency, even when turning the volume back up.

The issue remains even when EarTrumpet is exited, only exiting it beforehand prevents the issue from occurring. One way to fix it is to disable and re enable the audio device, although that only works sometimes, restarting always works.

The difference for me is that it happens across the entire system and all apps.

**Comment by thaurane** [comment] 2020-01-01 10:09
Same issue as described by martinsstuff. For me its the steam icon. Closing and restarting and reinstalling does not fix the issue. While this flickering is present ear trumpet is using as much as 20% of my CPU which is completely unacceptable and now requires me to uninstall it completely. This is a shame because ear trumpet has been my favorite for such a long time.

**Comment by thaurane** [comment] 2020-01-01 10:13
Same issue as described by martinsstuff but for me its the steam icon. Closing and restarting and reinstalling does not fix the issue. Trying to scroll other volumes does nothing. The slider will go up and down (not the number) and the volume doesn't actually change. Also while this flickering is present ear trumpet is using as much as 20% of my CPU.

edit: restarting steam fixed the issue. Others that have this issue should try killing the effected program and restart it.

**Closed** 2020-12-18 19:30 UTC
Labels: status: can't reproduce
