### ISSUE TITLE
Volume Mixer still opens in background when opened via hotkey

### ISSUE THREAD

**Issue by D4n2021** [File-New-Project/EarTrumpet#1421] opened 2023-07-28 03:17 UTC
### Summary

Using an "Open Mixer" keybinding to open the mixer (while the process already runs), the window opens in the background instead of in the foreground (which would be intended behaviour):

![grafik](https://github.com/File-New-Project/EarTrumpet/assets/20766261/e052d7d2-f42a-415e-8ace-1cd4259bc7ec)

### Steps to reproduce

Make sure EarTrumpet already runs, then set an "Open Mixer" keybinding, then close any open volume mixer, open some program in maximized mode (Firefox for example) and then press the keybinding. Volume Mixer window now opens in background.

### EarTrumpet version

2.2.2.0

### Windows version

19045.3208

**Comment by riverar** [comment] 2023-08-09 23:07
Hm, can't reproduce that here. Can you try another shortcut, like `CTRL+~`? Am curious if you see any change.

**Comment by riverar** [comment] 2023-08-28 05:30
This is related to https://github.com/File-New-Project/EarTrumpet/issues/311, not much we can do here. It's a Windows quirk. I've spoken to shell engineers and they have confirm the quirk; wouldn't expect it to be fixed any time soon sadly.

Closing this for now as there's nothing we can do, but feel free to keep the discussion going!

**Closed by riverar** 2023-08-28 05:30 UTC
