### ISSUE TITLE
Hotkey to Switch Audio Inputs/Outputs

### ISSUE THREAD

**Issue by YWI** [File-New-Project/EarTrumpet#469] opened 2020-03-01 03:49 UTC
I use my headset and speakers and if I had a hotkey to swtich from my headset to my speaker and the other way around it would make my life easier. Same thing for microphones.

Please consider ;)

**Comment by riverar** [comment] 2020-05-07 09:17
Popular request, closing as it's a dupe of #211. Thanks!

**Closed by riverar** 2020-05-07 09:17 UTC
