### ISSUE TITLE
Multiple instances of the same application

### ISSUE THREAD

**Issue by DeepanRajV** [File-New-Project/EarTrumpet#152] opened 2017-11-08 16:35 UTC
After windows 10 update to 1709 multiple instances of app started showing up...
for example 
1 Firefox where one primary and one for each tab with sound or flash player...
2 ms solitaire where one with 100% vol but has no effect, the other with the preset volume...
3 candy crush soda where one controls the click action volume and other the background music...
4 windows shell experience host pops up randomly...
![repo1](https://user-images.githubusercontent.com/31111065/32560541-e7b462f6-c4cf-11e7-94cc-ca81895d4645.png)

**Comment by DJCBS** [comment] 2017-11-20 00:00
Same is happening to me. I used to have Windows Store games silenced before 1709 and it always worked. After 1709, whenever I open up a game, it recognises the old setting but opens up a new channel that defaults to 100& volume and as soon as one closes the game, goes away, doesn't save and when opened again one has to silence it again.

And it's definitely something that Microsoft changed in 1709.

**Comment by riverar** [comment] 2017-11-20 00:00
Thanks, can you put together a solid set of repro steps that I can run through on another machine?

**Comment by DJCBS** [comment] 2017-11-20 00:12
Sure. As I've faced this mainly with games, let's use, for example, the freemium "Dragon Mania Legends" game by Gameloft.

1 - Install the game. EarTrumpet will recognise it and show its respective sound control.
2 - Silence the game. The game will remain silenced if you close it and open it again. So even if the normal game music and sounds are enabled, it will keep the entire app quiet.

However:

3 - Click "Free Gems". It will play you one of those "watch a 30 second ad and we'll give you a prize".

Now, before 1709:

- EarTrumpet still saw it as sound from the game and maintained it silenced.

After 1709:

- EarTrumpet doesn't silence it, opens the second channel of the game when you play the ad and blasts it at 100%. If you silence that too, it will remain silenced only until you restart or close the game. After that it will reset it back to normal.

It seems to me that, whatever Microsoft changed in 1709, is leading EarTrumpet to think that sounds that aren't native to the base app code are from a different app. That would explain, I think, why the OP also sees that happening on Solitaire and Candy Crush.

**Comment by GoldenTao** [comment] 2017-11-20 01:29
This is one we've found with pretty much anything that creates a new audio session. Games like Minesweeper do this when they play an Ad.  It could be the Microsoft Ad Framework, but we're still looking into this. At the moment I think it's a bug in Windows since they started working on spatial audio.

**Comment by Alainke2** [comment] 2017-11-20 14:56
I can confirm this. City Mania by Gameloft is another example. Even when muted with Eartrumpet, the in-game ads play full volume. I’m running the latest RS4 peview build 17040 on this pc.

I just tried that game on a machine running 1703 and there everything is muted as it should be.

So, it’s clear they’re either using some new api call or there’s a bug in the Windows framework. Can’t see this behavior as being by design.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: DJCBS <notifications@github.com>
Verzonden: Monday, November 20, 2017 1:12:05 AM
Aan: File-New-Project/EarTrumpet
CC: Subscribed
Onderwerp: Re: [File-New-Project/EarTrumpet] Multiple instances of the same application (#152)


Sure. As I've faced this mainly with games, let's use, for example, the freemium "Dragon Mania Legends" game by Gameloft.

1 - Install the game. EarTrumpet will recognise it and show its respective sound control.
2 - Silence the game. The game will remain silenced if you close it and open it again. So even if the normal game music and sounds are enabled, it will keep the entire app quiet.

However:

3 - Click "Free Gems". It will play you one of those "watch a 30 second ad and we'll give you a prize".

Now, before 1709:

  *   EarTrumpet still saw it as sound from the game and maintained it silenced.

After 1709:

  *   EarTrumpet doesn't silence it, opens the second channel of the game when you play the ad and blasts it at 100%. If you silence that too, it will remain silenced only until you restart or close the game. After that it will reset it back to normal.

It seems to me that, whatever Microsoft changed in 1709, is leading EarTrumpet to think that sounds that aren't native to the base app code are from a different app. That would explain, I think, why the OP also sees that happening on Solitaire and Candy Crush.

**Comment by Lunariz** [comment] 2017-11-24 15:16
Can confirm for Firefox, since the new update (which starts a thread for every tab), any audio playing tab is shown and controlled separately in EarTrumpet. This makes it very difficult to find which one to change!
The repro should be fairly easy:
On the latest firefox (Firefox Quantum or Firefox 57), simply open multiple tabs playing various youtube videos. Then open EarTrumpet, and multiple sliders for Firefox will appear
![image](https://user-images.githubusercontent.com/6254272/33216111-cd0931ce-d132-11e7-87ed-8b1dced3c2d5.png)

**Comment by Onepamopa** [comment] 2017-11-24 15:20
Well it would have been nice if the slidebars actually showed peak audio on each, the way volume mixer shows for each application.

**Comment by riverar** [comment] 2018-06-13 05:40
We made a lot of grouping changes in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp) and let us know if you have any further issues.

**Closed by riverar** 2018-06-13 05:40 UTC
Labels: bug, windows-bug
