### ISSUE TITLE
Mute is not saved for Microsoft Solitaire Collection

### ISSUE THREAD

**Issue by stevek123** [File-New-Project/EarTrumpet#88] opened 2016-10-01 22:03 UTC
I like to play with Microsoft Solitaire Collection (https://www.microsoft.com/store/apps/9wzdncrfhwd2), but there is no way in the game to mute it, so I use the latest EarTrumpet from the store to do it.

My problem is that every time I start the game, the mute and sound level is back to 100, and I have to mute it again.

**Comment by stevek123** [comment] 2016-10-02 00:17
The same goes for "Windows Shell Experience Host". Is this more like a feature, then a bug? :/

**Comment by riverar** [comment] 2016-10-05 08:32
Dupe of #31

**Comment by stevek123** [comment] 2016-10-06 16:22
Thank you very much! Is there going to be a solution implemented to solve this in the near future?

**Comment by riverar** [comment] 2016-10-06 16:32
Windows doesn't remember these settings, so we'd have to do something custom if we choose to do it at all. I don't think we're close to doing anything like this right now, but we'll evaluate it.

**Comment by GoldenTao** [comment] 2016-10-08 07:32
This one will be discussed/fixed in #31, please check back there for updates.

**Closed by GoldenTao** 2016-10-08 07:32 UTC
Labels: duplicate, enhancement
