### ISSUE TITLE
StoreApp->immediately Bluescreen - Webside Install runs but.... 

### ISSUE THREAD

**Issue by Timmih** [File-New-Project/EarTrumpet#86] opened 2016-09-29 08:13 UTC
Hi.

If i Install the App from the Store i get instantly a BlueScreen and after the Restart come this Error: [http://image.prntscr.com/image/95624385ac034ad5beba8511f51098a6.png](url).

If i use the latest Version from the Website the programm is Starting and Running but it doesnt show me the Forza Horizon 3 regulator and for this i need it :( The Volume Control from this game is terrible
Screen: http://image.prntscr.com/image/73d0a51d057e4a478e9d651cd14f98bb.png

I hope u can help me to fix the Store app or u can give me the Actually Version for Download :(

Greetings from Germany... Sry for my bad english but i hope u Understand.
Timmih

**Comment by GoldenTao** [comment] 2016-09-29 08:20
@Timmih Unfortunately this is a Windows/ATI Bug with all Centennial apps (like EarTrumpet) We've done some research and there isn't an easy fix we can do, We're waiting to hear back from Microsoft about how long the fix will take.

Duplicate of #84

**Comment by Timmih** [comment] 2016-09-29 08:31
Hi.
Thanks for the fast Answer and surprise i have a ATI/AMD GPU... 
I hope they can fix it.

greetings

**Closed** 2016-09-29 10:05 UTC
