### ISSUE TITLE
Audio Spikes Bug When Alt+Tab

### ISSUE THREAD

**Issue by ASTERION-1995** [File-New-Project/EarTrumpet#978] opened 2021-12-22 07:09 UTC
## Description
Volume is suddenly spiking to max volume, whenever i alt tab ing between desktop back to game (the spikes is happening if im back in the game, not when im in desktop), this bug happened when im playing Genshin Impact
The volume is back to normal volume after 3 second i alt tab ing to my desktop
And this spike only occurs when im using bluetooth headphones (SONY WH1000-XM4 latest software version)
My laptop is ROG G15 GA503QM 2021
Windows 11, ver. 21H2, OS Build : 22000.376

## Steps to reproduce
1. Open Genshin Impact
2. Alt+Tab to desktop
3. Alt+Tab back to Genshin Impact
4. Volume spiking to maximum

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746

**Comment by riverar** [comment] 2023-04-26 17:34
Can't reproduce this on EarTrumpet 2.2.2.36 / Windows 11 / latest Genshin update, using Bluetooth or RF. Maybe specific to the device? Closing for now but let me know if this is still happening or if you have more info. Thanks!

![image](https://user-images.githubusercontent.com/475132/234656755-6a0a80bb-0ba6-452e-9640-30399003777f.png)

**Closed by riverar** 2023-04-26 17:34 UTC
Labels: type: third-party-bug
