### ISSUE TITLE
EarTrumpet no longer works, can't be reinstalled

### ISSUE THREAD

**Issue by jematiga** [File-New-Project/EarTrumpet#412] opened 2019-09-05 04:19 UTC
Hi there, EarTrumpet used to work perfectly until recently (I am guessing after the windows updates)

- Icon no longer appears in tray
-- I used to be able to use restart the app and it would work - doesn't do anything.
- Reinstall doesn't seem to work either
-- I uninstalled to try and reinstall, but clicking install doesn't do anything from Microsoft App Store.

Is there a way to manually install and get it to work again? Thanks!

**Comment by Katoru** [comment] 2019-09-07 18:37
I have the same problem.

Windows 10 1903

**Comment by nicktheone** [comment] 2019-09-13 08:00
Same issue here after 1903 update. First the app crashed on startup because of the Mark of the Web thing on a font and after removing it I'm unable to reinstall it with an error code of 0x80073D05. A forked version of the app works perfectly (https://github.com/Nonononoki/EarTrumpet).

**Comment by Katoru** [comment] 2019-09-13 08:31
I somehow managed to get the Windows Store version to work. (Sorry if the english description of menus is not accurate, my windows is not in english)

In the past, i did modify the target drive on which new apps should be installed. I switched to E:
This might be what caused the problem for me.
I did went to Settings > Applications and looked for EarTrumpet application. Left clicked on it. Choose "Move application" i moved it back to C:\ and tada.

I heard that a lot of application form microsoft store couldn't bear to be installed anywhere else than C:\, which is a shame.

**Comment by nicktheone** [comment] 2019-09-13 08:48
Aside from the fact I'm unable to find this menu unfortunately the app has been already removed and now I can' reinstall it properly.

**Comment by riverar** [comment] 2019-11-26 00:42
Hey @jematiga @nicktheone @Katoru Are you all still having the same issue?

**Comment by nicktheone** [comment] 2019-11-26 18:41
Same. Still getting an error code 0x80073D05 when it's installing. Resorted to using a forked version downloaded directly from GitHub.

**Comment by pingzing** [comment] 2019-11-27 20:34
I was experiencing this as well. Did an uninstall in an attempt to clear out stray Notification Area entries, then couldn't reinstall. 

I was able to fix it by heading into `C:\Users\<MY USERNAME>\AppData\Local\Packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\` and clearing out what files remained. The culprit _seems_ like it might have been the cache files in `SystemAppData/Helium/`, but that's a guess, at best.

**Comment by nicktheone** [comment] 2019-11-27 21:15
I can't believe I didn't think about looking for some spare files and old cache. I thought it was a Store error and fixated on that unfruitfully. Thanks friend!

**Comment by ArsenicTouch** [comment] 2019-12-26 13:32
> I was experiencing this as well. Did an uninstall in an attempt to clear out stray Notification Area entries, then couldn't reinstall.
> 
> I was able to fix it by heading into `C:\Users\<MY USERNAME>\AppData\Local\Packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\` and clearing out what files remained. The culprit _seems_ like it might have been the files in `SystemAppData/Helium/` and `SystemAppData/Helium/Cache`, but that's a guess, at best.

You rock. Went in and delete the folder and was able to finally reinstall eartrumpet. (had license errors, uninstalled and then it wouldn't let me reinstall)

**Comment by David263** [comment] 2020-08-07 23:00
I'm having volume problems plus an error message when restarting Windows, so I just want to uninstall EarTrumpet. But I installed it using the Zip file, not Store. It is not listed as an installed program. Help?

**Comment by riverar** [comment] 2021-02-24 08:20
Closing. We can't reproduce this. Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. Thanks!

**Closed by riverar** 2021-02-24 08:20 UTC
Labels: status: can't reproduce
