### ISSUE TITLE
[REQUEST] An option to hide programs from the list

### ISSUE THREAD

**Issue by Inled** [File-New-Project/EarTrumpet#369] opened 2019-05-30 19:06 UTC
I think that an option to hideo progrmas such as discord or Steam wich I always use at a fixed level, would be great

**Comment by SullieLore** [comment] 2019-06-01 16:38
I think this would be a good addition to the program. I don't want to see Windows Sounds since they are perma-muted for instance.

**Comment by riverar** [comment] 2019-06-01 19:47
Closing, dupe of #263. We hear you though!

**Closed by riverar** 2019-06-01 19:47 UTC
Labels: type: feature-request
