### ISSUE TITLE
After Restart from pc the system volume is set to 100%

### ISSUE THREAD

**Issue by GGabi0101** [File-New-Project/EarTrumpet#1067] opened 2022-02-15 16:05 UTC
### Summary

I have to say, that i hate that the system volume is so loud. In my opinion it should stay at 10% forever. But every time when i restart my computer the System volume is back to 100%. The volume of every other program is normaly saved from earTrumpet...

Dont get me wrong, i love this tiny little extra for windows. it looks so natrual that nobody would notice that it is  a third party program. 

Thank you for your work and keep it up!
GG

### Steps to reproduce

every time when i restart my computer

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19042.1526

**Comment by JkleSXB** [comment] 2022-03-06 03:43
Hello, same thing here, and now even if I desinstall EarTrumpet the problem remains. Any clue on how to fix this ?

**Comment by riverar** [comment] 2022-03-06 06:18
Neither Windows or EarTrumpet save volume levels, so there's nothing to _fix_. Sorry. Dupe of #315.

**Closed by riverar** 2022-03-06 06:18 UTC
Labels: type: windows-bug
