### ISSUE TITLE
Mixer becoming bigger for no reason

### ISSUE THREAD

**Issue by Letrixix** [File-New-Project/EarTrumpet#990] opened 2022-01-07 14:39 UTC
(using dev version)

![image](https://user-images.githubusercontent.com/87038960/148559510-d405315b-9288-471f-b549-5b539410c659.png)

i didn't do nothing and it just became like this.

**Comment by riverar** [comment] 2022-01-08 04:36
Possible duplicates: #439 #447

Did you resume from sleep? Are you at something other than 100% DPI?

**Comment by Letrixix** [comment] 2022-01-08 13:02
No, i don't put almost never my pc on sleep and, dpi of what?

Il giorno sab 8 gen 2022 alle ore 05:37 Rafael Rivera <
***@***.***> ha scritto:

**Comment by riverar** [comment] 2022-01-11 22:13
Was just curious if your system DPI / scaling was set to something other than 100%.

Example from Windows 11:
![image](https://user-images.githubusercontent.com/475132/149029746-f1732087-dc2e-44e3-ab53-a6c62d865359.png)

**Comment by Letrixix** [comment] 2022-01-12 16:57
i have 150% on a 4k resolution. anyways, a lot of things happened: the
mixer seemed to become normal, but it was like moved to the right making it
"cut", and randomly it just returned back to normal.

Il giorno mar 11 gen 2022 alle ore 23:13 Rafael Rivera <
***@***.***> ha scritto:

**Comment by riverar** [comment] 2022-01-13 23:46
Got it. This is a dupe of #888 and fixed in dev builds. I'll push this out to all EarTrumpet users soon, thanks for reporting!

**Closed by riverar** 2022-01-13 23:46 UTC
