### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by spekulazarus** [File-New-Project/EarTrumpet#437] opened 2019-11-03 11:01 UTC
![image](https://user-images.githubusercontent.com/46869662/68084106-8c2b2080-fe31-11e9-9133-63b0fb4d672e.png)

Since yesterday the icons don't show up anymore (see image).
What can I do? I already restarted eartrumpet and my pc.
Thanks

**Comment by luffykazuma** [comment] 2019-11-06 14:14
Getting the same problem as well; the icon for VLC Media Player never showed up on the EarTrumpet GUI.

![image](https://user-images.githubusercontent.com/54678277/68305480-9a10b980-005c-11ea-89a2-3ba69a06b98f.png)

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-12 21:11
This happens on my system if Microangelo OnDisplay is installed: http://microangelo.us/free-download/change-vista-icons.asp It installs an icon handler shell extension (https://docs.microsoft.com/en-us/windows/win32/shell/how-to-create-icon-handlers) which causes icons in EarTrumpet to break. Can you guys find a workaround to show icons with it installed?

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-16 07:27
Update: It seems that Microangelo icon handler shell extension replaces the shell interface (IExtractIcon) that gets the icon from a file, but it only does it for the ANSI version IExtractIconA and not the Unicode version IExtractIconW. So the code needs to be updated to look for the ANSI interface if the Unicode is not found, and the icons will no longer be broken in EarTrumpet.

**Comment by riverar** [comment] 2021-09-16 07:32
@Gaurav-Original-ClassicShellTester Can you create a new issue for your particular problem? Thanks!

**Comment by Gaurav-Original-ClassicShellTester** [comment] 2021-09-16 08:36
Yes, sorry I wasn't sure if creating a separate issue for similar ones would be more annoying or less so I posted here. Created a separate issue now.

**Comment by LetsPlayNintendoITA** [comment] 2021-11-30 19:17
> This happens on my system if Microangelo OnDisplay is installed: http://microangelo.us/free-download/change-vista-icons.asp It installs an icon handler shell extension (https://docs.microsoft.com/en-us/windows/win32/shell/how-to-create-icon-handlers) which causes icons in EarTrumpet to break. Can you guys find a workaround to show icons with it installed?

thanks!

**Comment by riverar** [comment] 2023-01-26 21:07
Doing some issue cleanup, marking as duplicate of #384 (rounding up icon issues). Thanks!

**Closed by riverar** 2023-01-26 21:07 UTC
