### ISSUE TITLE
EarTrumpet's Mixer Window error

### ISSUE THREAD

**Issue by MasterGaeX** [File-New-Project/EarTrumpet#818] opened 2021-04-29 16:24 UTC
## Description
When I try to drag the EarTrumpet's mixer window, [this happens](https://drive.google.com/file/d/1DI_VxiKvhCUo2qqja2Qkn1X1ysp3e6da/view?usp=sharing). The cursor duplicates itself and drag the window where it wants. 

## Steps to reproduce
1. Right click on the EarTrumpet status icon
2. Click on Mixer on the menu that appears
3. Drag the windows

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.928

**Comment by riverar** [comment] 2021-04-29 18:41
Duplicate of #349 we have a fix in [dev builds](https://eartrumpet.app) if you'd like to try it out.

**Closed by riverar** 2021-04-29 18:41 UTC
Labels: type: bug
