### ISSUE TITLE
The application has stopped starting

### ISSUE THREAD

**Issue by BodyulCG** [File-New-Project/EarTrumpet#466] opened 2020-02-26 09:42 UTC
There are two errors .NET Runtime and Application Error in the event viewer.
I have Windows 10 1909.

```
Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Globalization.RegionInfo..ctor(Int32)
   at EarTrumpet.AppSettings.IsTelemetryEnabledByDefault()
   at EarTrumpet.AppSettings.get_IsTelemetryEnabled()
   at EarTrumpet.Diagnosis.ErrorReporter..ctor(EarTrumpet.AppSettings)
   at EarTrumpet.App.OnAppStartup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at EarTrumpet.App.Main()
```
```
Faulting application name: EarTrumpet.exe, version: 2.1.6.0, time stamp: 0x5e52ed0a
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0x54734dee
Exception code: 0xe0434352
Fault offset: 0x00113db2
Faulting process id: 0xd80
Faulting application start time: 0x01d5ec868ceef3dd
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.6.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 05235b96-8268-420f-8f7c-e0c57f7c06d5
Faulting package full name: 40459File-New-Project.EarTrumpet_2.1.6.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet
```

**Comment by riverar** [comment] 2020-02-26 10:04
@BodyulCG Looks like your first paste got cut off at the top, can you take another look at that?

**Comment by BodyulCG** [comment] 2020-02-26 10:08
> 
> 
> @BodyulCG Looks like your first paste got cut off at the top, can you take another look at that?

Yes, you're right, corrected.

**Comment by riverar** [comment] 2020-02-26 10:09
Ah ok. This is a duplicate of #465. I submitted a fix to the Store but it's taking _forever_ to get approved. Could go out in 10 minutes or another 10 hours. Sorry for the headache.

**Comment by riverar** [comment] 2020-02-26 19:50
Update has been released.

**Closed by riverar** 2020-02-26 19:50 UTC
