### ISSUE TITLE
EarTrumpet locks onto the mouse scrollwheel when in VR

### ISSUE THREAD

**Issue by KaleidonKep99** [File-New-Project/EarTrumpet#1199] opened 2022-07-30 13:43 UTC
### Summary

While I'm in VR, and controlling the desktop through a desktop overlay such as XSOverlay, I like to change the volume of the programs by using the virtual scrollwheel on my Index Controller's touchpad.

For some reason though, after doing it once, EarTrumpet seems to lock onto that scrollwheel input even when I'm focused on other windows, making the volume go up and down as I scroll on stuff like Chrome or Discord.

### Steps to reproduce

- Open EarTrumpet's volume control while in VR *(happens on SteamVR Desktop, XSOverlay and OVR Toolkit so far)*.
- Change the volume of something.
- Focus on something else.
- Scroll up and down on the focused window, the volume will start going up and down as well.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.1826

**Comment by riverar** [comment] 2022-07-30 19:52
Interesting, I'll have to try this in my headset.

Sounds like your mouse cursor is not moving away from the notification area/EarTrumpet icon.

**Comment by KaleidonKep99** [comment] 2022-07-30 20:34
> Interesting, I'll have to try this in my headset.
> 
> Sounds like your mouse cursor is not moving away from the notification area/EarTrumpet icon.

I don't think that's the case though, because I can interact with other things just fine, it's just that no matter what I do, the scrolling is always picked up by EarTrumpet even when I'm not focused on it.

**Comment by riverar** [comment] 2022-07-31 03:41
@KaleidonKep99 Hm, not seeing any issues here in SteamVR w/ the Desktop window open. I hovered over the icon in the notification area, scrolled, works normally. Then moved away, scrolled in other apps, no issues. Tried also using hand and controller, no issues.

Can you provide repro steps that I can follow in SteamVR Desktop? If you need me to get the other software, I can do that too. Thanks!

**Comment by riverar** [comment] 2022-08-21 04:14
Closing as dupe of #1119.

**Closed by riverar** 2022-08-21 04:14 UTC
Labels: status: can't reproduce
