### ISSUE TITLE
New Fluent Design Logo

### ISSUE THREAD

**Issue by akhilesh-balaji** [File-New-Project/EarTrumpet#551] opened 2020-08-24 06:25 UTC
Windows 10 apps have recently been migrating to more fluent design-style icons. However, some apps in the Microsoft store, do not have these fluent design icons, and it looks really out of place in the apps menu. How about a redesigned icon? I have designed a concept new icon for EarTrumpet, and you can find it here:
[Eartrumpet logos Presentation.pdf](https://github.com/File-New-Project/EarTrumpet/files/5116119/Eartrumpet.logos.Presentation.pdf)

Here is a Before/After comparison between the two:
![BeforeAfter](https://user-images.githubusercontent.com/69246693/91024251-4f752380-e615-11ea-8f0d-a0cece56bba8.png)

You can contact me if you are interested in all the files.

**Comment by Cyberdroid1** [comment] 2020-08-24 10:22
Looks nice!

**Comment by akhilesh-balaji** [comment] 2020-08-24 13:56
@Cyberdroid1 Thanks 😁

**Comment by riverar** [comment] 2020-08-26 03:58
Duplicate of #484, thanks!

**Closed by riverar** 2020-08-26 03:58 UTC

**Comment by akhilesh-balaji** [comment] 2020-08-26 10:51
@riverar Oh, so sorry. Didn't know there was aldready an issue.
