### ISSUE TITLE
Volume controls horizontally truncated when screen is scaled > 100%

### ISSUE THREAD

**Issue by doublehelix** [File-New-Project/EarTrumpet#1337] opened 2023-03-22 22:42 UTC
### Summary

My primary display (in multi-screen setup) is set to scale at 200%
![image](https://user-images.githubusercontent.com/355130/227053647-d56f9f51-fbe4-4826-ba34-f0e9c4adfa74.png)

As a result, the volume control popup is scaled, however the width of the popup does not fit the volume controls:
![image](https://user-images.githubusercontent.com/355130/227054225-7fb84fba-a1e6-438e-b352-7b3f45b94f36.png)

### Steps to reproduce

From the `System` > `Display` settings in control panel (Windows 11) scale any display to 200%.
Activate the volume popup.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1413

### Additional information

Related to the following parent group of issues:
 - #1304

**Comment by riverar** [comment] 2023-03-22 23:05
Did you sign out/in after changing the scale factor? Does restarting EarTrumpet resolve the issue?

**Comment by riverar** [comment] 2023-03-22 23:45
@doublehelix Don't forget my questions here, thanks!

**Comment by doublehelix** [comment] 2023-03-23 02:22
Will definitely test that in a moment. Thanks for the reminder. (Just started a process I have to wait for before I reboot).
Can confirm that adding/removing displays doesn't help, and changing the scale helps in the direction I change it. I.e. if I go from 200% to 150% if fits better, but not perfectly still.
Will update again after further tests.

**Comment by doublehelix** [comment] 2023-03-23 22:20
Confirmed that re-booting the system will reset all component window scaling.
![image](https://user-images.githubusercontent.com/355130/227376761-40986ad7-1a3b-45d3-8efd-aed52c632926.png)

However, changing scaling again requires a restart to fix.

Scaled up from 200% to 250%:
![image](https://user-images.githubusercontent.com/355130/227376986-422bd740-8af2-4450-ab7a-bdd82e629d9e.png)

Scaled back from 250% down to 200% (no restart):
![image](https://user-images.githubusercontent.com/355130/227377496-dd7d5e89-a34b-4538-804e-4b5af7d3bc2b.png)

**Comment by riverar** [comment] 2023-03-23 22:47
Does restarting the app (not Windows) resolve the issue too? I suspect this is an underlying UI framework issue rather than an EarTrumpet issue.

**Comment by doublehelix** [comment] 2023-03-28 00:52
Hey - finally confirmed it does indeed reset the scaling after restarting the app (should have tested that long ago!)

Hopefully this is related to combinations of DPICHANGED/GETDPISCALEDSIZE window messages.
I'd love to look into it, but need to dig through the code properly first ('cause we all have so much spare time right).

Cheers for the awesome software.

**Comment by riverar** [comment] 2023-04-09 17:48
Duplicate of #1337

Thanks for the data!

**Closed by riverar** 2023-04-09 17:48 UTC
